import math
import re

from .geometry import clip_contours_to_bed, contour_center, distance, format_float, read_svg
from .kinematics import bed_to_machine, ne_park_position, planned_contours, plan_contour_thetas, tool_to_command

def append_custom_command(lines, command):
    for raw_line in (command or "").replace(";", "\n").splitlines():
        line = raw_line.strip()
        if line and (not lines or lines[-1] != line):
            lines.append(line)


def append_pen_dwell(lines, settings):
    # Pause after an M3/M5 pen actuation so the pen reaches the paper (or lifts
    # clear) before motion resumes. grblHAL runs the next line immediately after
    # M3/M5, so without this the pen would drag or start a stroke mid-air. In Z
    # mode the pen move is itself a timed motion, so no dwell is needed.
    if settings.include_z:
        return
    ms = float(getattr(settings, "pen_cycle_ms", 0.0))
    if ms > 0:
        lines.append(f"G4 P{format_float(ms / 1000.0)}")


def format_xy_command(point, settings):
    x, y = tool_to_command(point, settings)
    return f"X{format_float(x)} Y{format_float(y)}"


def contours_to_gcode(contours, settings):
    axis = re.sub(r"[^A-Za-z]", "", settings.theta_axis.upper())[:1] or "A"
    center = contour_center(contours)
    contours = clip_contours_to_bed(contours, center, max(float(getattr(settings, "bed_diameter_mm", 457.2)) / 2.0 - float(getattr(settings, "bed_margin_mm", 0.0)), 0.0))
    lines = ["(Generated by svg_to_gcode.pyw)", "G21", "G90", f"G0 F{format_float(settings.travel_rate)}"]
    if settings.preview_xy_only:
        lines.append("(XY preview mode: theta axis omitted)")
    if settings.include_z:
        lines.append(f"G0 Z{format_float(settings.safe_z)}")
    else:
        append_custom_command(lines, settings.pen_up_command)
        append_pen_dwell(lines, settings)

    previous_theta = None
    previous_machine = None
    for planned in planned_contours(contours, settings, center):
        pts = planned["path"]
        thetas, strategies = plan_contour_thetas(pts, settings, previous_theta, center, previous_machine)
        if not thetas:
            continue
        first_theta = thetas[0]

        x0, y0 = bed_to_machine(pts[0], first_theta, center)
        first_motor_theta = first_theta * settings.theta_drive_ratio
        lines.append(f"(contour {planned['index'] + 1}{' reversed' if planned.get('reversed') else ''})")
        if settings.include_z:
            if settings.preview_xy_only:
                lines.append(f"G0 {format_xy_command((x0, y0), settings)} Z{format_float(settings.safe_z)}")
            else:
                lines.append(f"G0 {format_xy_command((x0, y0), settings)} {axis}{format_float(first_motor_theta)} Z{format_float(settings.safe_z)}")
            lines.append(f"G1 Z{format_float(settings.work_z)} F{format_float(settings.feed_rate)}")
        else:
            # Pen is already up here (initial lift, or the previous contour's
            # end lift), so travel straight to the start — no redundant M5/dwell.
            if settings.preview_xy_only:
                lines.append(f"G0 {format_xy_command((x0, y0), settings)}")
            else:
                lines.append(f"G0 {format_xy_command((x0, y0), settings)} {axis}{format_float(first_motor_theta)}")
            append_custom_command(lines, settings.pen_down_command)
            append_pen_dwell(lines, settings)
            lines.append(f"G1 F{format_float(settings.feed_rate)}")

        for k in range(len(pts) - 1):
            a, b = pts[k], pts[k + 1]
            if distance(a, b) <= 1e-9:
                continue
            theta = thetas[k + 1]
            strategy = strategies[k] or "tangent"
            x, y = bed_to_machine(b, theta, center)
            if settings.preview_xy_only:
                lines.append(f"G1 {format_xy_command((x, y), settings)} F{format_float(settings.feed_rate)} ({strategy})")
            else:
                motor_theta = theta * settings.theta_drive_ratio
                lines.append(f"G1 {format_xy_command((x, y), settings)} {axis}{format_float(motor_theta)} F{format_float(settings.feed_rate)} ({strategy})")
        previous_theta = thetas[-1]
        previous_machine = bed_to_machine(pts[-1], thetas[-1], center)

        if settings.include_z:
            lines.append(f"G0 Z{format_float(settings.safe_z)}")
        else:
            append_custom_command(lines, settings.pen_up_command)
            append_pen_dwell(lines, settings)
    if previous_machine is not None:
        park_x, park_y = ne_park_position(center, settings)
        if settings.preview_xy_only or previous_theta is None:
            lines.append(f"G0 {format_xy_command((park_x, park_y), settings)} (park NE)")
        else:
            motor_theta = previous_theta * settings.theta_drive_ratio
            lines.append(f"G0 {format_xy_command((park_x, park_y), settings)} {axis}{format_float(motor_theta)} (park NE)")
    lines.append("M2")
    return "\n".join(lines) + "\n"

def convert_file(svg_path, gcode_path, settings):
    contours = read_svg(svg_path, settings)
    if not contours:
        raise ValueError("No drawable SVG geometry was found.")
    gcode = contours_to_gcode(contours, settings)
    with open(gcode_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(gcode)
    return len(contours), len(gcode.splitlines())


def build_preview_moves(contours, settings):
    moves = []
    center = contour_center(contours)
    contours = clip_contours_to_bed(contours, center, max(float(getattr(settings, "bed_diameter_mm", 457.2)) / 2.0 - float(getattr(settings, "bed_margin_mm", 0.0)), 0.0))
    last_machine_end = None
    previous_theta = None
    previous_motor_theta = 0.0
    axis = re.sub(r"[^A-Za-z]", "", settings.theta_axis.upper())[:1] or "A"
    for planned in planned_contours(contours, settings, center):
        contour_index = planned["index"]
        path = planned["path"]
        thetas, strategies = plan_contour_thetas(path, settings, previous_theta, center, last_machine_end)
        if not thetas:
            continue
        first_theta = thetas[0]

        machine_start = bed_to_machine(path[0], first_theta, center)
        command_start = tool_to_command(machine_start, settings)
        first_motor_theta = first_theta * settings.theta_drive_ratio
        if last_machine_end is None:
            pen_up = f"G0 Z{format_float(settings.safe_z)}" if settings.include_z else (settings.pen_up_command or "(pen up)")
            moves.append({"type": "pen_up", "start": machine_start, "end": machine_start, "command_start": command_start, "command_end": command_start, "bed_start": path[0], "bed_end": path[0], "contour": contour_index, "duration_ms": max(float(getattr(settings, "pen_cycle_ms", 100.0)), 0.0), "gcode": pen_up})
            g0 = f"G0 {format_xy_command(machine_start, settings)}"
            if not settings.preview_xy_only:
                g0 += f" {axis}{format_float(first_motor_theta)}"
            initial_motor_delta = abs(first_motor_theta - previous_motor_theta)
            initial_travel_ms = initial_motor_delta / max(settings.travel_rate, 1e-9) * 60000.0
            moves.append({"type": "travel", "start": machine_start, "end": machine_start, "command_start": command_start, "command_end": command_start, "bed_start": path[0], "bed_end": path[0], "bed_theta": first_theta, "motor_theta": first_motor_theta, "contour": contour_index, "duration_ms": initial_travel_ms, "motion_length": initial_motor_delta, "xy_length": 0.0, "gcode": g0})
            previous_motor_theta = first_motor_theta
        elif distance(last_machine_end, machine_start) > 1e-9 or abs(first_motor_theta - previous_motor_theta) > 1e-9:
            travel_xy = distance(last_machine_end, machine_start)
            travel_motor = abs(first_motor_theta - previous_motor_theta)
            travel_len = math.hypot(travel_xy, travel_motor)
            travel_ms = travel_len / max(settings.travel_rate, 1e-9) * 60000.0
            g0 = f"G0 {format_xy_command(machine_start, settings)}"
            if not settings.preview_xy_only:
                g0 += f" {axis}{format_float(first_motor_theta)}"
            moves.append({"type": "travel", "start": last_machine_end, "end": machine_start, "command_start": tool_to_command(last_machine_end, settings), "command_end": command_start, "bed_start": path[0], "bed_end": path[0], "bed_theta": first_theta, "motor_theta": first_motor_theta, "contour": contour_index, "duration_ms": travel_ms, "motion_length": travel_len, "xy_length": travel_xy, "gcode": g0})
            previous_motor_theta = first_motor_theta

        pen_down = f"G1 Z{format_float(settings.work_z)} F{format_float(settings.feed_rate)}" if settings.include_z else (settings.pen_down_command or "(pen down)")
        moves.append({"type": "pen_down", "start": machine_start, "end": machine_start, "command_start": command_start, "command_end": command_start, "bed_start": path[0], "bed_end": path[0], "contour": contour_index, "duration_ms": max(float(getattr(settings, "pen_cycle_ms", 100.0)), 0.0), "gcode": pen_down})
        moves.append({"type": "feed", "start": machine_start, "end": machine_start, "command_start": command_start, "command_end": command_start, "bed_start": path[0], "bed_end": path[0], "contour": contour_index, "duration_ms": 0, "gcode": f"G1 F{format_float(settings.feed_rate)}"})

        last_machine = machine_start
        for k in range(len(path) - 1):
            a, b = path[k], path[k + 1]
            if distance(a, b) <= 1e-9:
                continue
            bed_theta = thetas[k + 1]
            strategy = strategies[k] or "tangent"
            machine_end = bed_to_machine(b, bed_theta, center)
            command_end = tool_to_command(machine_end, settings)
            motor_theta = bed_theta * settings.theta_drive_ratio
            xy_len = distance(last_machine, machine_end)
            motor_delta = abs(motor_theta - previous_motor_theta)
            move_len = math.hypot(xy_len, motor_delta)
            move_ms = move_len / max(settings.feed_rate, 1e-9) * 60000.0
            previous_motor_theta = motor_theta
            if settings.preview_xy_only:
                gcode = f"G1 {format_xy_command(machine_end, settings)} F{format_float(settings.feed_rate)} ({strategy})"
            else:
                gcode = f"G1 {format_xy_command(machine_end, settings)} {axis}{format_float(motor_theta)} F{format_float(settings.feed_rate)} ({strategy})"
            moves.append({
                "type": "draw",
                "start": last_machine,
                "end": machine_end,
                "command_start": tool_to_command(last_machine, settings),
                "command_end": command_end,
                "bed_start": a,
                "bed_end": b,
                "bed_theta": bed_theta,
                "motor_theta": motor_theta,
                "strategy": strategy,
                "contour": contour_index,
                "duration_ms": move_ms,
                "motion_length": move_len,
                "xy_length": xy_len,
                "gcode": gcode,
            })
            last_machine = machine_end
        previous_theta = thetas[-1]

        pen_up = f"G0 Z{format_float(settings.safe_z)}" if settings.include_z else (settings.pen_up_command or "(pen up)")
        moves.append({"type": "pen_up", "start": last_machine, "end": last_machine, "command_start": tool_to_command(last_machine, settings), "command_end": tool_to_command(last_machine, settings), "bed_start": path[-1], "bed_end": path[-1], "contour": contour_index, "duration_ms": max(float(getattr(settings, "pen_cycle_ms", 100.0)), 0.0), "gcode": pen_up})
        last_machine_end = last_machine
    if last_machine_end is not None:
        park = ne_park_position(center, settings)
        command_park = tool_to_command(park, settings)
        park_motor_theta = previous_theta * settings.theta_drive_ratio if previous_theta is not None else 0.0
        park_xy = distance(last_machine_end, park)
        park_motor_delta = abs(park_motor_theta - previous_motor_theta)
        park_len = math.hypot(park_xy, park_motor_delta)
        park_ms = park_len / max(settings.travel_rate, 1e-9) * 60000.0
        gcode = f"G0 {format_xy_command(park, settings)}"
        if not settings.preview_xy_only and previous_theta is not None:
            gcode += f" {axis}{format_float(park_motor_theta)}"
        gcode += " (park NE)"
        moves.append({
            "type": "travel",
            "start": last_machine_end,
            "end": park,
            "command_start": tool_to_command(last_machine_end, settings),
            "command_end": command_park,
            "bed_start": park,
            "bed_end": park,
            "bed_theta": previous_theta if previous_theta is not None else 0.0,
            "motor_theta": park_motor_theta,
            "contour": None,
            "duration_ms": park_ms,
            "motion_length": park_len,
            "xy_length": park_xy,
            "gcode": gcode,
        })
    return moves
