import math
import re

from .cancellation import check_cancelled
from .geometry import clip_contours_to_bed, contour_center, distance, format_float, normalized_hatch_pattern, read_svg
from .kinematics import bed_to_machine, ne_park_position, plan_radius_aware_draw_feed, planned_contours, plan_contour_thetas
from .settings import pattern_size_override, pattern_size_values, validate_settings

def append_custom_command(lines, command):
    for raw_line in (command or "").replace(";", "\n").splitlines():
        line = raw_line.strip()
        if line and (not lines or lines[-1] != line):
            lines.append(line)


def pen_up_duration_ms(settings):
    return max(float(getattr(settings, "pen_up_ms", 300.0)), 0.0)


def pen_down_duration_ms(settings):
    return max(float(getattr(settings, "pen_down_ms", 600.0)), 0.0)


def append_pen_dwell(lines, settings, direction):
    # Pause after an M3/M5 pen actuation so the pen reaches the paper (or lifts
    # clear) before motion resumes. grblHAL runs the next line immediately after
    # M3/M5, so without this the pen would drag or start a stroke mid-air. In Z
    # mode the pen move is itself a timed motion, so no dwell is needed.
    if settings.include_z:
        return
    ms = pen_down_duration_ms(settings) if direction == "down" else pen_up_duration_ms(settings)
    if ms > 0:
        lines.append(f"G4 P{format_float(ms / 1000.0)}")


def format_xy_command(point):
    x, y = point
    return f"X{format_float(x)} Y{format_float(y)}"


def bridge_motion(prev_machine, prev_motor_theta, next_machine, next_motor_theta, center, settings):
    pattern = normalized_hatch_pattern(getattr(settings, "hatch_pattern", "crosshatch"))
    bridge_patterns = {"concentric", "triangular", "diamonds", "hexagonal"}
    if pattern not in bridge_patterns:
        return None
    xy_len = distance(prev_machine, next_machine)
    spacing = max(float(getattr(settings, "hatch_spacing_mm", 0.0)), 0.0)
    spacing = pattern_size_override(pattern, spacing, pattern_size_values(settings))
    if spacing <= 0.0:
        return None
    pattern_gap = spacing * (1.35 if pattern == "concentric" else 0.85)
    max_gap = max(pattern_gap, float(getattr(settings, "pen_diameter_mm", 0.0)) * 6.0)
    if xy_len <= 1e-9 or xy_len > max_gap:
        return None
    motor_delta = abs(next_motor_theta - prev_motor_theta)
    feed_plan = plan_radius_aware_draw_feed(
        prev_machine,
        next_machine,
        center,
        xy_len,
        motor_delta,
        settings,
    )
    motion_len = feed_plan["motion_length"]
    draw_ms = feed_plan["duration_ms"]
    travel_ms = motion_len / max(float(getattr(settings, "travel_rate", 1.0)), 1e-9) * 60000.0
    lift_lower_ms = pen_up_duration_ms(settings) + pen_down_duration_ms(settings)
    if draw_ms >= travel_ms + lift_lower_ms:
        return None
    return {
        "xy_len": xy_len,
        "motor_delta": motor_delta,
        "motion_len": motion_len,
        "duration_ms": draw_ms,
        "feed_plan": feed_plan,
    }


def plan_program(contours, settings, cancel_check=None):
    """Plan clipped contours and theta positions once for all program consumers."""
    validate_settings(settings)
    check_cancelled(cancel_check)
    center = contour_center(contours)
    clipped_contours = clip_contours_to_bed(
        contours,
        center,
        max(float(getattr(settings, "bed_diameter_mm", 457.2)) / 2.0 - float(getattr(settings, "bed_margin_mm", 0.0)), 0.0),
        cancel_check,
    )
    planned_jobs = []
    previous_theta = None
    previous_machine = None
    for planned in planned_contours(clipped_contours, settings, center, cancel_check):
        check_cancelled(cancel_check)
        points = planned["path"]
        thetas, strategies = plan_contour_thetas(
            points,
            settings,
            previous_theta,
            center,
            previous_machine,
            cancel_check,
        )
        if not thetas:
            continue
        planned_jobs.append((planned, points, thetas, strategies))
        previous_theta = thetas[-1]
        previous_machine = bed_to_machine(points[-1], thetas[-1], center)
    return {
        "center": center,
        "contours": clipped_contours,
        "planned_jobs": planned_jobs,
    }


def contours_to_gcode(contours, settings, program_plan=None):
    validate_settings(settings)
    program_plan = program_plan or plan_program(contours, settings)
    axis = re.sub(r"[^A-Za-z]", "", settings.theta_axis.upper())[:1] or "A"
    center = program_plan["center"]
    # Establish the drawing file's own units, distance, feed, plane, and work
    # coordinate modes. ioSender streams these lines; it does not repair modal
    # state inherited from an earlier console command or macro.
    lines = [
        "(Generated by svg_to_gcode.pyw)",
        "G21",
        "G90",
        "G94",
        "G17",
        "G54",
        f"G0 F{format_float(settings.travel_rate)}",
    ]
    if settings.include_z:
        lines.append(f"G0 Z{format_float(settings.safe_z)}")
    else:
        append_custom_command(lines, settings.pen_up_command)
        append_pen_dwell(lines, settings, "up")

    previous_machine = None
    previous_motor_theta = 0.0
    pen_is_down = False
    for planned, pts, thetas, strategies in program_plan["planned_jobs"]:
        first_theta = thetas[0]

        x0, y0 = bed_to_machine(pts[0], first_theta, center)
        first_motor_theta = first_theta * settings.theta_drive_ratio
        lines.append(f"(contour {planned['index'] + 1}{' reversed' if planned.get('reversed') else ''})")
        bridge = None if previous_machine is None else bridge_motion(
            previous_machine,
            previous_motor_theta,
            (x0, y0),
            first_motor_theta,
            center,
            settings,
        )
        if bridge and pen_is_down:
            bridge_feed = bridge["feed_plan"]["feed_rate"]
            lines.append(f"G1 {format_xy_command((x0, y0))} {axis}{format_float(first_motor_theta)} F{format_float(bridge_feed)} (keep-down bridge)")
        else:
            if pen_is_down:
                if settings.include_z:
                    lines.append(f"G0 Z{format_float(settings.safe_z)}")
                else:
                    append_custom_command(lines, settings.pen_up_command)
                    append_pen_dwell(lines, settings, "up")
                pen_is_down = False
            if settings.include_z:
                lines.append(f"G0 {format_xy_command((x0, y0))} {axis}{format_float(first_motor_theta)} Z{format_float(settings.safe_z)}")
                lines.append(f"G1 Z{format_float(settings.work_z)} F{format_float(settings.feed_rate)}")
            else:
                lines.append(f"G0 {format_xy_command((x0, y0))} {axis}{format_float(first_motor_theta)}")
                append_custom_command(lines, settings.pen_down_command)
                append_pen_dwell(lines, settings, "down")
                lines.append(f"G1 F{format_float(settings.feed_rate)}")
            pen_is_down = True

        for k in range(len(pts) - 1):
            a, b = pts[k], pts[k + 1]
            if distance(a, b) <= 1e-9:
                continue
            theta = thetas[k + 1]
            strategy = strategies[k] or "tangent"
            x, y = bed_to_machine(b, theta, center)
            motor_theta = theta * settings.theta_drive_ratio
            start_theta = thetas[k]
            start_machine = bed_to_machine(a, start_theta, center)
            start_motor_theta = start_theta * settings.theta_drive_ratio
            feed_plan = plan_radius_aware_draw_feed(
                a,
                b,
                center,
                distance(start_machine, (x, y)),
                motor_theta - start_motor_theta,
                settings,
            )
            lines.append(f"G1 {format_xy_command((x, y))} {axis}{format_float(motor_theta)} F{format_float(feed_plan['feed_rate'])} ({strategy})")
        previous_theta = thetas[-1]
        previous_machine = bed_to_machine(pts[-1], thetas[-1], center)
        previous_motor_theta = previous_theta * settings.theta_drive_ratio

    if pen_is_down:
        if settings.include_z:
            lines.append(f"G0 Z{format_float(settings.safe_z)}")
        else:
            append_custom_command(lines, settings.pen_up_command)
            append_pen_dwell(lines, settings, "up")
    if previous_machine is not None:
        park_x, park_y = ne_park_position(center, settings)
        if previous_theta is None:
            lines.append(f"G0 {format_xy_command((park_x, park_y))} (park NE)")
        else:
            motor_theta = previous_theta * settings.theta_drive_ratio
            lines.append(f"G0 {format_xy_command((park_x, park_y))} {axis}{format_float(motor_theta)} (park NE)")
    lines.append("M2")
    return "\n".join(lines) + "\n"

def convert_file(svg_path, gcode_path, settings):
    contours = read_svg(svg_path, settings)
    if not contours:
        raise ValueError("No drawable SVG geometry was found.")
    gcode = contours_to_gcode(contours, settings)
    with open(gcode_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(gcode)
    return len(contours), len(gcode.splitlines())


def build_preview_moves(contours, settings, cancel_check=None, program_plan=None):
    validate_settings(settings)
    check_cancelled(cancel_check)
    moves = []
    program_plan = program_plan or plan_program(contours, settings, cancel_check)
    center = program_plan["center"]
    last_machine_end = None
    previous_theta = None
    previous_motor_theta = 0.0
    axis = re.sub(r"[^A-Za-z]", "", settings.theta_axis.upper())[:1] or "A"
    previous_theta = None
    previous_motor_theta = 0.0
    pen_is_down = False
    for planned, path, thetas, strategies in program_plan["planned_jobs"]:
        check_cancelled(cancel_check)
        contour_index = planned["index"]
        first_theta = thetas[0]

        machine_start = bed_to_machine(path[0], first_theta, center)
        first_motor_theta = first_theta * settings.theta_drive_ratio
        bridge = None if last_machine_end is None else bridge_motion(
            last_machine_end,
            previous_motor_theta,
            machine_start,
            first_motor_theta,
            center,
            settings,
        )
        if last_machine_end is None:
            pen_up = f"G0 Z{format_float(settings.safe_z)}" if settings.include_z else (settings.pen_up_command or "(pen up)")
            moves.append({"type": "pen_up", "start": machine_start, "end": machine_start, "bed_start": path[0], "bed_end": path[0], "contour": contour_index, "duration_ms": pen_up_duration_ms(settings), "gcode": pen_up})
            g0 = f"G0 {format_xy_command(machine_start)}"
            g0 += f" {axis}{format_float(first_motor_theta)}"
            initial_motor_delta = abs(first_motor_theta - previous_motor_theta)
            initial_travel_ms = initial_motor_delta / max(settings.travel_rate, 1e-9) * 60000.0
            moves.append({"type": "travel", "start": machine_start, "end": machine_start, "bed_start": path[0], "bed_end": path[0], "bed_theta": first_theta, "motor_theta": first_motor_theta, "contour": contour_index, "duration_ms": initial_travel_ms, "motion_length": initial_motor_delta, "xy_length": 0.0, "gcode": g0})
            previous_motor_theta = first_motor_theta
        elif bridge and pen_is_down:
            bridge_feed = bridge["feed_plan"]["feed_rate"]
            gcode = f"G1 {format_xy_command(machine_start)}"
            gcode += f" {axis}{format_float(first_motor_theta)}"
            gcode += f" F{format_float(bridge_feed)} (keep-down bridge)"
            moves.append({
                "type": "draw",
                "start": last_machine_end,
                "end": machine_start,
                "bed_start": path[0],
                "bed_end": path[0],
                "bed_theta": first_theta,
                "motor_theta": first_motor_theta,
                "strategy": "keep_down_bridge",
                "contour": contour_index,
                "duration_ms": bridge["duration_ms"],
                "motion_length": bridge["motion_len"],
                "xy_length": bridge["xy_len"],
                "feed_rate": bridge_feed,
                "radius_mm": bridge["feed_plan"]["radius_mm"],
                "tangential_speed_mm_min": bridge["feed_plan"]["tangential_speed_mm_min"],
                "limited_by": bridge["feed_plan"]["limited_by"],
                "gcode": gcode,
            })
            previous_motor_theta = first_motor_theta
        else:
            if pen_is_down:
                pen_up = f"G0 Z{format_float(settings.safe_z)}" if settings.include_z else (settings.pen_up_command or "(pen up)")
                moves.append({"type": "pen_up", "start": last_machine_end, "end": last_machine_end, "bed_start": path[0], "bed_end": path[0], "contour": contour_index, "duration_ms": pen_up_duration_ms(settings), "gcode": pen_up})
                pen_is_down = False
            if distance(last_machine_end, machine_start) > 1e-9 or abs(first_motor_theta - previous_motor_theta) > 1e-9:
                travel_xy = distance(last_machine_end, machine_start)
                travel_motor = abs(first_motor_theta - previous_motor_theta)
                travel_len = math.hypot(travel_xy, travel_motor)
                travel_ms = travel_len / max(settings.travel_rate, 1e-9) * 60000.0
                g0 = f"G0 {format_xy_command(machine_start)}"
                g0 += f" {axis}{format_float(first_motor_theta)}"
                moves.append({"type": "travel", "start": last_machine_end, "end": machine_start, "bed_start": path[0], "bed_end": path[0], "bed_theta": first_theta, "motor_theta": first_motor_theta, "contour": contour_index, "duration_ms": travel_ms, "motion_length": travel_len, "xy_length": travel_xy, "gcode": g0})
                previous_motor_theta = first_motor_theta

        if not pen_is_down:
            pen_down = f"G1 Z{format_float(settings.work_z)} F{format_float(settings.feed_rate)}" if settings.include_z else (settings.pen_down_command or "(pen down)")
            moves.append({"type": "pen_down", "start": machine_start, "end": machine_start, "bed_start": path[0], "bed_end": path[0], "contour": contour_index, "duration_ms": pen_down_duration_ms(settings), "gcode": pen_down})
            moves.append({"type": "feed", "start": machine_start, "end": machine_start, "bed_start": path[0], "bed_end": path[0], "contour": contour_index, "duration_ms": 0, "gcode": f"G1 F{format_float(settings.feed_rate)}"})
            pen_is_down = True

        last_machine = machine_start
        for k in range(len(path) - 1):
            check_cancelled(cancel_check)
            a, b = path[k], path[k + 1]
            if distance(a, b) <= 1e-9:
                continue
            bed_theta = thetas[k + 1]
            strategy = strategies[k] or "tangent"
            machine_end = bed_to_machine(b, bed_theta, center)
            motor_theta = bed_theta * settings.theta_drive_ratio
            xy_len = distance(last_machine, machine_end)
            motor_delta = motor_theta - previous_motor_theta
            feed_plan = plan_radius_aware_draw_feed(
                a,
                b,
                center,
                xy_len,
                motor_delta,
                settings,
            )
            move_len = feed_plan["motion_length"]
            move_ms = feed_plan["duration_ms"]
            previous_motor_theta = motor_theta
            gcode = f"G1 {format_xy_command(machine_end)} {axis}{format_float(motor_theta)} F{format_float(feed_plan['feed_rate'])} ({strategy})"
            moves.append({
                "type": "draw",
                "start": last_machine,
                "end": machine_end,
                "bed_start": a,
                "bed_end": b,
                "bed_theta": bed_theta,
                "motor_theta": motor_theta,
                "strategy": strategy,
                "contour": contour_index,
                "duration_ms": move_ms,
                "motion_length": move_len,
                "xy_length": xy_len,
                "feed_rate": feed_plan["feed_rate"],
                "radius_mm": feed_plan["radius_mm"],
                "tangential_speed_mm_min": feed_plan["tangential_speed_mm_min"],
                "limited_by": feed_plan["limited_by"],
                "gcode": gcode,
            })
            last_machine = machine_end
        previous_theta = thetas[-1]
        last_machine_end = last_machine
    if last_machine_end is not None:
        if pen_is_down:
            pen_up = f"G0 Z{format_float(settings.safe_z)}" if settings.include_z else (settings.pen_up_command or "(pen up)")
            moves.append({"type": "pen_up", "start": last_machine_end, "end": last_machine_end, "bed_start": last_machine_end, "bed_end": last_machine_end, "contour": None, "duration_ms": pen_up_duration_ms(settings), "gcode": pen_up})
        park = ne_park_position(center, settings)
        park_motor_theta = previous_theta * settings.theta_drive_ratio if previous_theta is not None else 0.0
        park_xy = distance(last_machine_end, park)
        park_motor_delta = abs(park_motor_theta - previous_motor_theta)
        park_len = math.hypot(park_xy, park_motor_delta)
        park_ms = park_len / max(settings.travel_rate, 1e-9) * 60000.0
        gcode = f"G0 {format_xy_command(park)}"
        if previous_theta is not None:
            gcode += f" {axis}{format_float(park_motor_theta)}"
        gcode += " (park NE)"
        moves.append({
            "type": "travel",
            "start": last_machine_end,
            "end": park,
            "bed_start": park,
            "bed_end": park,
            "bed_theta": previous_theta if previous_theta is not None else 0.0,
            "motor_theta": park_motor_theta,
            "contour": None,
            "duration_ms": park_ms,
            "motion_length": park_len,
            "xy_length": park_xy,
            "gcode": gcode,
        })
    return moves
