import math
import re
from xml.etree import ElementTree as ET
from .cancellation import check_cancelled
from .settings import CELL_PATTERNS, CELL_SPACING_SCALE, HATCH_PATTERNS, pattern_size_values
from .shading import (
    dot_mark_contours,
    greedy_single_line,
    halftone_contours,
    stipple_mark_radius,
    stipple_points,
)

GEOMETRY_VERSION = "2.4-photo-shading"  # stipple, halftone and single-line tone fills

# Drop contours shorter than this (in on-paper mm). Clipping the infill lattice
# to a polygon boundary leaves sub-pen-width slivers that draw an M3/M5 "dot"
# with no visible contribution; they only cost pen cycles and print time.
MIN_FILL_SEGMENT_LENGTH = 1.0

# Inset the fill region by this much (on-paper mm, roughly the pen radius) before
# clipping the lattice so infill does not bleed into surrounding blank borders.
FILL_INSET_MM = 0.2


class FillTrail(list):
    """An open infill trail generated by this module's fill code.

    Keep-down bridging is only safe between generated fill trails. An artwork's
    own open strokes (hatch marks, petals, fan ribs) are geometrically identical
    to a fill trail, and bridging those draws connectors across blank paper -
    the 2026-09-30 mandala defect. The tag rides on the contour object through
    the geometry pipeline; if a transform loses it, bridging is simply refused
    for that contour, which costs pen cycles and never correctness.
    """


def retag_contour(source, points):
    """Rebuild ``points`` as a :class:`FillTrail` when ``source`` was one."""
    points = list(points)
    return FillTrail(points) if isinstance(source, FillTrail) else points


COMMAND_RE = re.compile(r"[MmZzLlHhVvCcSsQqTtAa]|[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?")
NUMBER_RE = re.compile(r"[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?")
UNIT_RE = re.compile(r"^\s*([-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?)([a-zA-Z%]*)\s*$")

class Matrix:
    def __init__(self, a=1.0, b=0.0, c=0.0, d=1.0, e=0.0, f=0.0):
        self.a, self.b, self.c, self.d, self.e, self.f = a, b, c, d, e, f

    def __matmul__(self, other):
        return Matrix(
            self.a * other.a + self.c * other.b,
            self.b * other.a + self.d * other.b,
            self.a * other.c + self.c * other.d,
            self.b * other.c + self.d * other.d,
            self.a * other.e + self.c * other.f + self.e,
            self.b * other.e + self.d * other.f + self.f,
        )

    def apply(self, x, y):
        return (self.a * x + self.c * y + self.e, self.b * x + self.d * y + self.f)


def strip_ns(tag):
    return tag.split("}", 1)[-1] if "}" in tag else tag


def parse_length(value, default=0.0):
    if value is None:
        return default
    match = UNIT_RE.match(value)
    if not match:
        return default
    number = float(match.group(1))
    unit = match.group(2)
    factors = {"": 1.0, "px": 25.4 / 96.0, "mm": 1.0, "cm": 10.0, "in": 25.4, "pt": 25.4 / 72.0, "pc": 25.4 / 6.0}
    return number * factors.get(unit, 1.0)


def parse_points(points):
    nums = [float(x) for x in NUMBER_RE.findall(points or "")]
    return list(zip(nums[0::2], nums[1::2]))


def parse_transform(text):
    if not text:
        return Matrix()
    result = Matrix()
    for name, raw_args in re.findall(r"([a-zA-Z]+)\(([^)]*)\)", text):
        args = [float(x) for x in NUMBER_RE.findall(raw_args)]
        name = name.lower()
        m = Matrix()
        if name == "matrix" and len(args) >= 6:
            m = Matrix(*args[:6])
        elif name == "translate":
            m = Matrix(e=args[0] if args else 0.0, f=args[1] if len(args) > 1 else 0.0)
        elif name == "scale":
            sx = args[0] if args else 1.0
            sy = args[1] if len(args) > 1 else sx
            m = Matrix(a=sx, d=sy)
        elif name == "rotate" and args:
            angle = math.radians(args[0])
            rot = Matrix(math.cos(angle), math.sin(angle), -math.sin(angle), math.cos(angle), 0.0, 0.0)
            if len(args) >= 3:
                cx, cy = args[1], args[2]
                m = Matrix(e=cx, f=cy) @ rot @ Matrix(e=-cx, f=-cy)
            else:
                m = rot
        elif name == "skewx" and args:
            m = Matrix(c=math.tan(math.radians(args[0])))
        elif name == "skewy" and args:
            m = Matrix(b=math.tan(math.radians(args[0])))
        result = result @ m
    return result


def use_href(element):
    return element.get("href") or element.get("{http://www.w3.org/1999/xlink}href") or element.get("xlink:href")


# Presentation properties that inherit down the SVG element tree.
#
# The converter used to read presentation values from the element alone, so a
# wrapper such as `<g fill="none" stroke="#000" stroke-width="0.7">` was
# invisible to it. That wrapper is how Illustrator, Inkscape, and this project's
# own sample generators emit single-pen line art. Every child then fell back to
# the SVG initial fill of black, so outline paths were treated as solid filled
# regions and their interiors were hatched -- which also made each child count
# as "visible" purely because of that phantom fill. Resolving the inherited
# values fixes the fill regions and the visibility test together.
#
# Line art is still fillable, but explicitly: an element that declares no
# visible fill contributes the regions enclosed by its *closed* outlines (see
# `closed_outline_regions`). That keeps a stroke-only path from being hatched
# as if its whole bounding shape were solid, while still giving `fill="none"`
# artwork interior fill that stays inside the drawn outlines.
INHERITED_STYLE_PROPERTIES = (
    "fill",
    "fill-opacity",
    "stroke",
    "stroke-opacity",
    "stroke-width",
    "visibility",
    # `opacity` composites a whole subtree in the SVG rendering model rather
    # than inheriting, but propagating it approximates a group opacity far
    # better than ignoring it and hatching a 50%-transparent group at full
    # darkness.
    "opacity",
)


def own_style_value(element, name):
    """The property as declared on this element only, or None."""
    if element.get(name) is not None:
        return element.get(name)
    style = element.get("style") or ""
    for part in style.split(";"):
        if ":" not in part:
            continue
        key, value = part.split(":", 1)
        if key.strip() == name:
            return value.strip()
    return None


def style_value(element, name, inherited=None):
    """Resolve a presentation property the way an SVG renderer would.

    *inherited* carries the resolved style of the element's ancestors, so a
    property declared once on a wrapping group reaches its children. Falling
    through to None preserves the specification's initial values -- notably
    `fill: black` for an element that declares no fill anywhere.
    """
    value = own_style_value(element, name)
    if value is not None:
        return value
    if inherited:
        return inherited.get(name)
    return None


def inherited_style(parent_style, element):
    """Extend *parent_style* with the inheritable properties on *element*."""
    style = dict(parent_style or {})
    for name in INHERITED_STYLE_PROPERTIES:
        value = own_style_value(element, name)
        if value is not None:
            style[name] = value
    return style


def style_hidden(element, inherited=None):
    """True when an element and its subtree render nothing."""
    # `display` is not inherited; it suppresses the element and its children.
    display = own_style_value(element, "display")
    if display is not None and display.strip().lower() == "none":
        return True
    visibility = style_value(element, "visibility", inherited)
    return visibility is not None and visibility.strip().lower() in ("hidden", "collapse")


def stroke_width(element, inherited=None):
    value = style_value(element, "stroke-width", inherited)
    if not value:
        return 0.0
    return parse_length(value, 0.0)


def has_visible_stroke(element, inherited=None):
    stroke = style_value(element, "stroke", inherited)
    return (
        stroke is not None
        and stroke.strip().lower() != "none"
        and stroke_width(element, inherited) > 0
    )


def has_visible_fill(element, inherited=None):
    fill = style_value(element, "fill", inherited)
    if fill is not None and fill.strip().lower() == "none":
        return False
    opacity = style_value(element, "fill-opacity", inherited)
    if opacity is not None:
        try:
            if float(opacity) <= 0:
                return False
        except ValueError:
            pass
    return True


def parse_svg_color(value):
    if value is None:
        return (0.0, 0.0, 0.0)
    text = value.strip().lower()
    if not text or text == "none" or text.startswith("url("):
        return None
    named = {
        "black": (0.0, 0.0, 0.0),
        "white": (1.0, 1.0, 1.0),
        "red": (1.0, 0.0, 0.0),
        "green": (0.0, 0.5019607843, 0.0),
        "blue": (0.0, 0.0, 1.0),
        "gray": (0.5019607843, 0.5019607843, 0.5019607843),
        "grey": (0.5019607843, 0.5019607843, 0.5019607843),
    }
    if text in named:
        return named[text]
    if text.startswith("#"):
        raw = text[1:]
        if len(raw) == 3:
            raw = "".join(ch * 2 for ch in raw)
        if len(raw) >= 6:
            try:
                return tuple(int(raw[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
            except ValueError:
                return None
    match = re.match(r"rgba?\(([^)]*)\)", text)
    if match:
        parts = [part.strip() for part in match.group(1).split(",")]
        if len(parts) >= 3:
            out = []
            for part in parts[:3]:
                if part.endswith("%"):
                    out.append(max(0.0, min(float(part[:-1]) / 100.0, 1.0)))
                else:
                    out.append(max(0.0, min(float(part) / 255.0, 1.0)))
            return tuple(out)
    return None


def fill_darkness(element, inherited=None):
    color = parse_svg_color(style_value(element, "fill", inherited))
    if color is None:
        color = (0.0, 0.0, 0.0)
    r, g, b = color
    luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b
    darkness = 1.0 - luminance
    opacity = 1.0
    for name in ("fill-opacity", "opacity"):
        value = style_value(element, name, inherited)
        if value is None:
            continue
        try:
            opacity *= max(0.0, min(float(value), 1.0))
        except ValueError:
            pass
    return max(0.0, min(darkness * opacity, 1.0))


def stroke_darkness(element, inherited=None):
    color = parse_svg_color(style_value(element, "stroke", inherited))
    if color is None:
        return 0.0
    r, g, b = color
    luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b
    opacity = 1.0
    for name in ("stroke-opacity", "opacity"):
        value = style_value(element, name, inherited)
        if value is None:
            continue
        try:
            opacity *= max(0.0, min(float(value), 1.0))
        except ValueError:
            pass
    return max(0.0, min((1.0 - luminance) * opacity, 1.0))


def _element_is_visible(element, inherited=None):
    if has_visible_fill(element, inherited) and fill_darkness(element, inherited) > 1e-9:
        return True
    stroke = style_value(element, "stroke", inherited)
    return (
        stroke is not None
        and stroke.strip().lower() != "none"
        and stroke_darkness(element, inherited) > 1e-9
    )


# Elements the converter can turn into pen geometry. `text` is deliberately
# absent because the converter does not shape glyphs.
DRAWABLE_TAGS = ("path", "line", "polyline", "polygon", "rect", "circle", "ellipse")

# A photo or a scan is a valid input: it has no vector geometry, so it is always
# hatched from its rendered tone. The Qt app supplies the image itself.
RASTER_IMAGE_EXTENSIONS = frozenset(
    (".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff", ".gif")
)


def is_raster_image(path):
    """True when *path* is an image file rather than SVG artwork."""
    return str(path).strip().lower().endswith(tuple(RASTER_IMAGE_EXTENSIONS))


def svg_fill_sources(svg_path):
    """Classify how an SVG declares its artwork without parsing path geometry.

    Cheap enough to run while a file is selected: it walks the element tree,
    resolves inherited presentation values, and counts drawable elements by the
    fill geometry they contribute.

    Returns a dict with:

    * ``filled`` - elements that contribute a filled region to hatch.
    * ``outline`` - elements drawn only by a visible stroke. Their closed
      outlines still bound a fillable region.
    * ``image`` - embedded raster images, whose tone the vector path cannot see.
    * ``gradient`` - elements filled by a paint-server reference (``url(#...)``),
      which the fill parser reads as the SVG initial black instead of the
      gradient a renderer would show.
    """
    if is_raster_image(svg_path):
        # Nothing to parse: the whole file is tone the vector path cannot see.
        return {"filled": 0, "outline": 0, "image": 1, "gradient": 0}
    tree = ET.parse(svg_path)
    root = tree.getroot()
    id_map = {node.get("id"): node for node in root.iter() if node.get("id")}
    counts = {"filled": 0, "outline": 0, "image": 0, "gradient": 0}

    def walk(node, style, referenced=False, seen=None):
        seen = seen or set()
        tag = strip_ns(node.tag)
        if tag in ("defs", "symbol") and not referenced:
            return
        if style_hidden(node, style):
            return
        resolved = inherited_style(style, node)
        if tag == "use":
            href = use_href(node)
            if href and href.startswith("#"):
                target_id = href[1:]
                target = id_map.get(target_id)
                if target is not None and target_id not in seen:
                    walk(target, resolved, True, seen | {target_id})
            return
        if tag == "image":
            counts["image"] += 1
        fill = own_style_value(node, "fill")
        if fill is None:
            fill = resolved.get("fill") if resolved else None
        if fill is not None and fill.strip().lower().startswith("url("):
            counts["gradient"] += 1
        if tag in DRAWABLE_TAGS and _element_is_visible(node, resolved):
            counts["filled" if has_visible_fill(node, resolved) else "outline"] += 1
        for child in list(node):
            walk(child, resolved, referenced, seen)

    walk(root, {})
    return counts


def resolve_fill_source(settings, svg_path):
    """Return whether this SVG should be hatched as ``shapes`` or ``tone``.

    ``fill_source = auto`` uses the vector shapes for ordinary SVG artwork and
    falls back to the rendered image only when the tone lives somewhere the
    vector path cannot see it: an embedded raster image, or a gradient /
    pattern paint server. Everything else - filled traces, logos, and line art
    with closed outlines - stays on the vector path, where fill is clipped
    inside the drawn regions and cannot run over them.
    """
    source = str(getattr(settings, "fill_source", "auto") or "auto").strip().lower()
    if is_raster_image(svg_path):
        # A raster has no vector regions to hatch, whatever the field says.
        return "tone"
    if source in ("shapes", "tone"):
        return source
    sources = svg_fill_sources(svg_path)
    if sources["image"] or sources["gradient"]:
        return "tone"
    return "shapes"


def hatch_angles_for_tone(base_angle, levels, angle_step, darkness):
    levels = max(1, int(levels))
    active = max(0, min(levels, int(math.ceil(darkness * levels))))
    return [base_angle + i * angle_step for i in range(active)]


HATCH_PATTERN_ALIASES = {
    "line": "linear",
    "lines": "linear",
    "rectilinear": "linear",
    "hatch": "linear",
    "cross": "crosshatch",
    "cross_hatch": "crosshatch",
    "grid": "crosshatch",
    "diag": "diagonal",
    "diagonal_cross": "diagonal_crosshatch",
    "diagonal_cross_hatch": "diagonal_crosshatch",
    "diamond": "diamonds",
    "triangle": "triangular",
    "triangles": "triangular",
    "tri": "triangular",
    "hex": "hexagonal",
    "hexagon": "hexagonal",
    "honeycomb": "hexagonal",
    "circle": "circles",
    "dot": "dots",
    "stipple": "stipple",
    "stippling": "stipple",
    "pointillism": "stipple",
    "halftone": "halftone",
    "half_tone": "halftone",
    "half-tone": "halftone",
    "screen": "halftone",
    "tsp": "tsp",
    "single_line": "tsp",
    "single-line": "tsp",
    "singleline": "tsp",
    "oneline": "tsp",
    "one_line": "tsp",
    "wave": "waves",
    "sine": "waves",
    "sinusoidal": "waves",
    "gradient": "sine_gradient",
    "gradient_wave": "sine_gradient",
    "gradient_waves": "sine_gradient",
    "sine_gradient": "sine_gradient",
    "sine_wave_gradient": "sine_gradient",
    "continuous_sine": "sine_gradient",
    "isometric": "cubic",
    "iso": "cubic",
    "cube": "cubic",
    "concentric_ring": "concentric",
    "rings": "concentric",
    "inset": "concentric",
}

# The settings model owns the list of selectable patterns; the resolver must
# accept exactly the same names or a pattern could be offered and then silently
# fall back to crosshatch.
SUPPORTED_HATCH_PATTERNS = frozenset(HATCH_PATTERNS)


def normalized_hatch_pattern(pattern):
    """Return the canonical pattern id for a value, an alias, or a UI label.

    Labels such as `gradient waves (sine_gradient)` come from
    `settings.HATCH_PATTERN_LABELS`; the text before the parenthesis is tried
    first, then the text inside it, which keeps the combo's readable labels
    round-tripping to the stored value.
    """
    raw = str(pattern or "crosshatch").strip()
    candidates = []
    if "(" in raw:
        head, _, tail = raw.partition("(")
        candidates.append(head)
        candidates.append(tail.rstrip(") "))
    candidates.append(raw)
    for candidate in candidates:
        text = candidate.strip().lower().replace("-", "_").replace(" ", "_")
        if not text:
            continue
        if text in HATCH_PATTERN_ALIASES:
            return HATCH_PATTERN_ALIASES[text]
        if text in SUPPORTED_HATCH_PATTERNS:
            return text
    return "crosshatch"


def pattern_angles(base_angle, levels, angle_step, darkness, pattern):
    pattern = normalized_hatch_pattern(pattern)
    if pattern == "linear":
        return [base_angle]
    elif pattern == "crosshatch":
        offsets = (0.0, 90.0)
    elif pattern == "diagonal":
        return [base_angle + 45.0]
    elif pattern == "diagonal_crosshatch":
        offsets = (45.0, 135.0)
    elif pattern == "triangular":
        offsets = (0.0, 60.0, 120.0)
    else:
        return [base_angle]
    return [base_angle + offset for offset in offsets]


def active_shade_layers(levels, darkness):
    levels = max(1, int(levels))
    return max(0, min(levels, int(math.ceil(max(0.0, min(float(darkness), 1.0)) * levels))))


def density_spacing(spacing, levels, darkness):
    active = active_shade_layers(levels, darkness)
    if active <= 0:
        return None
    return max(float(spacing) / math.sqrt(active), 1e-6)


def point_in_polygon(point, polygon):
    x, y = point
    inside = False
    pts = polygon
    if len(pts) < 3:
        return False
    for a, b in zip(pts, pts[1:] + pts[:1]):
        x1, y1 = a
        x2, y2 = b
        if (y1 > y) != (y2 > y):
            # Edge straddles the horizontal ray, so y1 != y2 and the ratio below
            # is a well-behaved value in [0, 1]. Clamping the denominator with
            # max(..., eps) is wrong for downward edges (it flips the sign and
            # produces a huge intersection), so divide by (y2 - y1) directly.
            x_intersect = x1 + (x2 - x1) * (y - y1) / (y2 - y1)
            if x < x_intersect:
                inside = not inside
    return inside


def point_on_segment(point, a, b, tol=1e-7):
    px, py = point
    ax, ay = a
    bx, by = b
    dx, dy = bx - ax, by - ay
    length2 = dx * dx + dy * dy
    if length2 <= tol * tol:
        return math.hypot(px - ax, py - ay) <= tol
    cross = (px - ax) * dy - (py - ay) * dx
    if abs(cross) > tol * math.sqrt(length2):
        return False
    dot = (px - ax) * dx + (py - ay) * dy
    return -tol <= dot <= length2 + tol


def point_on_polygon_boundary(point, polygon, tol=1e-7):
    if len(polygon) < 2:
        return False
    pts = polygon if polygon[0] == polygon[-1] else polygon + [polygon[0]]
    return any(point_on_segment(point, a, b, tol) for a, b in zip(pts, pts[1:]))


def point_in_region(point, polygons):
    if any(point_on_polygon_boundary(point, polygon) for polygon in polygons):
        return True
    return sum(1 for polygon in polygons if point_in_polygon(point, polygon)) % 2 == 1


# Spatial index for the fill hot paths.
#
# A compound path traced from a bitmap can carry thousands of subpaths (the F15
# cutaway has 4,875 and the spirit logo 5,243). The fill code used to test every
# one of them against every hatch row and every inset query, which is quadratic
# in the subpath count: 23.8 M containment tests just to classify outer
# boundaries from holes, and ~7 M segment/edge intersections per hatch angle.
#
# The grid changes no geometry. A query returns a *superset* of the polygons
# whose bounding box can contain the point or overlap the segment, and the
# caller still runs the same exact predicates -- point_in_polygon, the segment
# intersection test, the even-odd parity accumulation. Only the number of
# evaluations drops.
#
# Below _FILL_INDEX_MIN_POLYGONS the grid is not built, so the single-polygon
# and small-region call sites behave exactly as they did before.
_FILL_INDEX_MIN_POLYGONS = 8
_FILL_INDEX_MAX_CELLS = 128


class _PolygonGrid:
    def __init__(self, polygons):
        self.count = len(polygons)
        self.bounds = []
        # Closed edge lists are built once here and reused by every hatch row
        # instead of being rebuilt per clip call.
        self.closed = []
        for polygon in polygons:
            if len(polygon) < 3:
                self.bounds.append(None)
                self.closed.append(None)
                continue
            xs = [p[0] for p in polygon]
            ys = [p[1] for p in polygon]
            self.bounds.append((min(xs), min(ys), max(xs), max(ys)))
            self.closed.append(
                polygon if polygon[0] == polygon[-1] else polygon + [polygon[0]]
            )
        self.enabled = False
        self.cells = None
        self.cols = 0
        self.cell_w = 1.0
        self.cell_h = 1.0
        self.lo_x = 0.0
        self.lo_y = 0.0
        self.hi_x = 0.0
        self.hi_y = 0.0
        self.stamp = [0] * self.count
        self.generation = 0
        boxes = [box for box in self.bounds if box is not None]
        if self.count < _FILL_INDEX_MIN_POLYGONS or not boxes:
            return
        lo_x = min(box[0] for box in boxes)
        lo_y = min(box[1] for box in boxes)
        hi_x = max(box[2] for box in boxes)
        hi_y = max(box[3] for box in boxes)
        if hi_x <= lo_x or hi_y <= lo_y:
            return
        span = min(max(1, math.isqrt(self.count)), _FILL_INDEX_MAX_CELLS)
        rows = span
        self.cols = span
        self.cell_w = (hi_x - lo_x) / span
        self.cell_h = (hi_y - lo_y) / rows
        self.lo_x, self.lo_y = lo_x, lo_y
        self.hi_x, self.hi_y = hi_x, hi_y
        self.cells = [None] * (span * rows)
        for index, box in enumerate(self.bounds):
            if box is None:
                continue
            c0, c1, r0, r1 = self._cells_for_box(box)
            for row in range(r0, r1 + 1):
                base = row * span
                for col in range(c0, c1 + 1):
                    bucket = self.cells[base + col]
                    if bucket is None:
                        self.cells[base + col] = [index]
                    else:
                        bucket.append(index)
        self.enabled = True

    def _clamp_col(self, value):
        return max(0, min(int(value), self.cols - 1))

    def _clamp_row(self, value):
        rows = len(self.cells) // self.cols
        return max(0, min(int(value), rows - 1))

    def _cells_for_box(self, box):
        return (
            self._clamp_col((box[0] - self.lo_x) / self.cell_w),
            self._clamp_col((box[2] - self.lo_x) / self.cell_w),
            self._clamp_row((box[1] - self.lo_y) / self.cell_h),
            self._clamp_row((box[3] - self.lo_y) / self.cell_h),
        )

    def _collect(self, c0, c1, r0, r1):
        self.generation += 1
        generation = self.generation
        stamp = self.stamp
        found = []
        cells = self.cells
        cols = self.cols
        for row in range(r0, r1 + 1):
            base = row * cols
            for col in range(c0, c1 + 1):
                bucket = cells[base + col]
                if not bucket:
                    continue
                for index in bucket:
                    if stamp[index] != generation:
                        stamp[index] = generation
                        found.append(index)
        return found

    def candidates_for_point(self, point):
        """Polygons whose bounding box may contain *point*."""
        if not self.enabled:
            return range(self.count)
        x, y = point
        if x < self.lo_x or x > self.hi_x or y < self.lo_y or y > self.hi_y:
            # Outside the overall bounding box, so outside every polygon.
            return ()
        c0, c1, r0, r1 = self._cells_for_box((x, y, x, y))
        return self._collect(c0, c1, r0, r1)

    def candidates_for_segment(self, a, b):
        """Polygons whose bounding box may overlap segment *a*-*b*."""
        if not self.enabled:
            return range(self.count)
        ax, ay = a
        bx, by = b
        box = (min(ax, bx), min(ay, by), max(ax, bx), max(ay, by))
        return self._collect(*self._cells_for_box(box))


def _point_in_polygons_even_odd(point, polygons, index=None):
    # Even-odd containment without the boundary scan. The boundary check only
    # matters for points that sit exactly on an edge, which is measure-zero for
    # a regular fill lattice; the per-edge scan it performs is otherwise pure
    # overhead in the fill hot path.
    candidates = range(len(polygons)) if index is None else index.candidates_for_point(point)
    inside = False
    for j in candidates:
        if point_in_polygon(point, polygons[j]):
            inside = not inside
    return inside


def clip_segment_to_region(a, b, polygons, index=None, pull_back=0.0):
    if not polygons:
        return []
    ax, ay = a
    bx, by = b
    dx, dy = bx - ax, by - ay
    ts = [0.0, 1.0]
    if index is None:
        candidates = range(len(polygons))
        closed = [None] * len(polygons)
    else:
        candidates = index.candidates_for_segment(a, b)
        closed = index.closed
    for j in candidates:
        pts = closed[j]
        if pts is None:
            polygon = polygons[j]
            if len(polygon) < 3:
                continue
            pts = polygon if polygon[0] == polygon[-1] else polygon + [polygon[0]]
            closed[j] = pts
        for p1, p2 in zip(pts, pts[1:]):
            ex, ey = p2[0] - p1[0], p2[1] - p1[1]
            denom = dx * ey - dy * ex
            if abs(denom) <= 1e-12:
                continue
            qx, qy = p1[0] - ax, p1[1] - ay
            t = (qx * ey - qy * ex) / denom
            u = (qx * dy - qy * dx) / denom
            if -1e-9 <= t <= 1.0 + 1e-9 and -1e-9 <= u <= 1.0 + 1e-9:
                ts.append(max(0.0, min(1.0, t)))
    ts = sorted(ts)
    deduped = []
    for t in ts:
        if not deduped or abs(t - deduped[-1]) > 1e-7:
            deduped.append(t)
    length = math.hypot(dx, dy)
    pull = (pull_back / length) if (pull_back > 0.0 and length > 1e-12) else 0.0
    segments = []
    for t0, t1 in zip(deduped, deduped[1:]):
        if t1 - t0 <= 1e-7:
            continue
        mid = (t0 + t1) / 2.0
        mid_point = (ax + dx * mid, ay + dy * mid)
        if not _point_in_polygons_even_odd(mid_point, polygons, index):
            continue
        # `pull_back` shortens the ends the clip created so the pen stops just
        # short of the boundary instead of touching it. The lattice is clipped
        # to the true fill region, so this can only shorten a pass -- it can
        # never move ink outside the region, which is what offsetting the
        # region itself used to do.
        s0, s1 = t0, t1
        if pull > 0.0:
            if t0 > 0.0:
                s0 = t0 + pull
            if t1 < 1.0:
                s1 = t1 - pull
            if s1 - s0 <= 1e-7:
                continue
        segments.append([
            (ax + dx * s0, ay + dy * s0),
            (ax + dx * s1, ay + dy * s1),
        ])
    return segments


def clip_segment_to_polygon(a, b, polygon):
    return clip_segment_to_region(a, b, [polygon])


def clip_polyline_to_region(points, polygons):
    clipped = []
    for a, b in zip(points, points[1:]):
        clipped.extend(clip_segment_to_region(a, b, polygons))
    return clipped


def clip_polyline_to_polygon(points, polygon):
    return clip_polyline_to_region(points, [polygon])


def chain_segments_to_paths(segments, precision=5):
    """Turn independent line segments into longer pen-down paths.

    The lattice generators naturally produce a graph. A greedy edge traversal
    reduces pen cycles by walking connected unused edges until it reaches a dead
    end/branch exhaustion. Edges are still drawn once; the ordering just changes
    from one contour per edge to one contour per graph trail.
    """
    clean = []
    for segment in segments:
        if len(segment) < 2:
            continue
        a, b = segment[0], segment[-1]
        if distance(a, b) > 1e-9:
            clean.append((a, b))
    if not clean:
        return []

    def key(point):
        return (round(point[0], precision), round(point[1], precision))

    points = {}
    adjacency = {}
    for index, (a, b) in enumerate(clean):
        ka, kb = key(a), key(b)
        points.setdefault(ka, a)
        points.setdefault(kb, b)
        adjacency.setdefault(ka, []).append((index, kb))
        adjacency.setdefault(kb, []).append((index, ka))

    unused = set(range(len(clean)))

    def unused_degree(k):
        return sum(1 for edge_index, _other in adjacency.get(k, ()) if edge_index in unused)

    def choose_start():
        odd = [k for k in adjacency if unused_degree(k) % 2 == 1 and unused_degree(k) > 0]
        if odd:
            return min(odd, key=lambda k: unused_degree(k))
        return next((k for k in adjacency if unused_degree(k) > 0), None)

    def take_next(k, previous_key=None):
        candidates = [(edge_index, other) for edge_index, other in adjacency.get(k, ()) if edge_index in unused]
        if not candidates:
            return None
        if previous_key is not None and len(candidates) > 1:
            non_backtrack = [item for item in candidates if item[1] != previous_key]
            if non_backtrack:
                candidates = non_backtrack
        return min(candidates, key=lambda item: unused_degree(item[1]))

    paths = []
    while unused:
        start = choose_start()
        if start is None:
            break
        path_keys = [start]
        current = start
        previous = None
        while True:
            item = take_next(current, previous)
            if item is None:
                break
            edge_index, other = item
            unused.remove(edge_index)
            previous, current = current, other
            path_keys.append(current)
        if len(path_keys) >= 2:
            paths.append([points[k] for k in path_keys])
    return paths


def rotated_region_bounds(polygons, angle_deg):
    ang = math.radians(angle_deg)
    cs, sn = math.cos(-ang), math.sin(-ang)
    points = [(x * cs - y * sn, x * sn + y * cs) for polygon in polygons for x, y in polygon]
    if not points:
        return (0.0, 0.0, 0.0, 0.0)
    return (
        min(x for x, _ in points),
        min(y for _, y in points),
        max(x for x, _ in points),
        max(y for _, y in points),
    )


def line_region_contours(polygons, spacing, angle_deg=0.0, cancel_check=None, pull_back=0.0):
    if spacing <= 0 or not polygons:
        return []
    ang = math.radians(angle_deg)
    ca, sa = math.cos(ang), math.sin(ang)
    min_x, min_y, max_x, max_y = rotated_region_bounds(polygons, angle_deg)
    if max_y <= min_y:
        return []

    def world(x, y):
        return (x * ca - y * sa, x * sa + y * ca)

    # Built once for the whole angle family. Every row below then tests only the
    # polygons whose bounding box can reach that row instead of all of them.
    index = _PolygonGrid(polygons)
    contours = []
    # Snap to global grid so multiple angle families phase-align correctly
    # (all families share reference lines at multiples of spacing from origin)
    y = math.floor(min_y / spacing) * spacing
    row = 0
    while y <= max_y:
        check_cancelled(cancel_check)
        start = world(min_x - spacing, y)
        end = world(max_x + spacing, y)
        segments = clip_segment_to_region(start, end, polygons, index, pull_back)
        if row % 2:
            segments = [[seg[1], seg[0]] for seg in reversed(segments)]
        contours.extend(segments)
        y += spacing
        row += 1
    return contours


def mark_grid_contours(polygons, spacing, angle_deg=0.0, mark="dots", cancel_check=None):
    if spacing <= 0 or not polygons:
        return []
    ang = math.radians(angle_deg)
    cs, sn = math.cos(-ang), math.sin(-ang)
    ca, sa = math.cos(ang), math.sin(ang)
    min_x, min_y, max_x, max_y = rotated_region_bounds(polygons, angle_deg)
    margin = spacing * 2.0
    min_x -= margin
    max_x += margin
    min_y -= margin
    max_y += margin
    circle_radius = max(spacing * 0.16, 0.05)
    dot_radius = max(spacing * 0.055, 0.03)
    row_step = spacing * math.sqrt(3.0) / 2.0
    steps = 10
    contours = []

    def world(x, y):
        return (x * ca - y * sa, x * sa + y * ca)

    # Snap to global grid
    y = math.floor((min_y - margin) / row_step) * row_step + row_step * 0.5
    row = 0
    while y <= max_y:
        check_cancelled(cancel_check)
        x_origin = math.floor((min_x - margin) / spacing) * spacing
        x = x_origin + spacing * (0.5 if row % 2 == 0 else 1.0)
        while x <= max_x:
            check_cancelled(cancel_check)
            center = world(x, y)
            if mark == "circles":
                circle = [
                    (
                        center[0] + math.cos(2.0 * math.pi * i / steps) * circle_radius,
                        center[1] + math.sin(2.0 * math.pi * i / steps) * circle_radius,
                    )
                    for i in range(steps + 1)
                ]
                contours.extend(clip_polyline_to_region(circle, polygons))
            elif point_in_region(center, polygons):
                dot = [
                    (center[0] - dot_radius, center[1]),
                    (center[0] + dot_radius, center[1]),
                ]
                contours.extend(clip_segment_to_region(dot[0], dot[1], polygons))
            x += spacing
        y += row_step
        row += 1
    return contours


def tile_shape_contours(polygons, spacing, angle_deg=0.0, shape="diamonds", cancel_check=None):
    if spacing <= 0 or not polygons:
        return []
    ang = math.radians(angle_deg)
    cs, sn = math.cos(-ang), math.sin(-ang)
    ca, sa = math.cos(ang), math.sin(ang)
    min_x, min_y, max_x, max_y = rotated_region_bounds(polygons, angle_deg)
    margin = spacing * 2.0
    min_x -= margin
    max_x += margin
    min_y -= margin
    max_y += margin
    contours = []

    def world(x, y):
        return (x * ca - y * sa, x * sa + y * ca)

    def add_clipped_polyline(points):
        shaped = [world(x, y) for x, y in points]
        contours.extend(clip_polyline_to_region(shaped, polygons))

    seen_segments = set()

    def add_clipped_segment(a, b):
        key_a = (round(a[0], 6), round(a[1], 6))
        key_b = (round(b[0], 6), round(b[1], 6))
        key = tuple(sorted((key_a, key_b)))
        if key in seen_segments:
            return
        seen_segments.add(key)
        contours.extend(clip_segment_to_region(world(*a), world(*b), polygons))

    def add_grid_segment(a, b):
        add_clipped_segment(a, b)

    if shape == "circles":
        radius = max(spacing * 0.5, 0.05)
        steps = 18
        row_step = radius * math.sqrt(3.0)
        # Snap to global grid so pattern is independent of polygon position
        y = math.floor((min_y - radius) / row_step) * row_step
        row = 0
        while y <= max_y + radius:
            check_cancelled(cancel_check)
            x_origin = math.floor((min_x - radius) / (radius * 2.0)) * (radius * 2.0)
            x = x_origin + (radius if row % 2 else 0.0)
            while x <= max_x + radius:
                check_cancelled(cancel_check)
                add_clipped_polyline([
                    (
                        x + math.cos(2.0 * math.pi * i / steps) * radius,
                        y + math.sin(2.0 * math.pi * i / steps) * radius,
                    )
                    for i in range(steps + 1)
                ])
                x += radius * 2.0
            y += row_step
            row += 1
        return contours

    if shape == "hexagonal":
        radius = max(spacing * 0.5, 0.05)
        x_step = radius * 1.5
        y_step = radius * math.sqrt(3.0)
        # Snap to global grid
        x_origin = math.floor((min_x - radius) / x_step) * x_step
        col = 0
        x = x_origin
        while x <= max_x + radius:
            check_cancelled(cancel_check)
            y_base = math.floor((min_y - radius) / y_step) * y_step
            y = y_base + (y_step * 0.5 if col % 2 else 0.0)
            while y <= max_y + radius:
                check_cancelled(cancel_check)
                vertices = [
                    (
                        x + math.cos(math.radians(60.0 * i)) * radius,
                        y + math.sin(math.radians(60.0 * i)) * radius,
                    )
                    for i in range(7)
                ]
                for a, b in zip(vertices, vertices[1:]):
                    add_clipped_segment(a, b)
                y += y_step
            x += x_step
            col += 1
        return chain_segments_to_paths(contours)

    if shape == "triangular":
        side = max(spacing, 0.05)
        row_step = side * math.sqrt(3.0) / 2.0
        j_min = int(math.floor((min_y - row_step) / row_step)) - 1
        j_max = int(math.ceil((max_y + row_step) / row_step)) + 1
        # point(i, j) = ((i + j * 0.5) * side, j * row_step). Account for the
        # j-dependent horizontal offset when bounding i so a tall region does
        # not over-generate columns.
        i_min = int(math.floor((min_x - side) / side - j_max * 0.5)) - 1
        i_max = int(math.ceil((max_x + side) / side - j_min * 0.5)) + 1

        def point(i, j):
            return ((i + j * 0.5) * side, j * row_step)

        for j in range(j_min, j_max + 1):
            check_cancelled(cancel_check)
            for i in range(i_min, i_max + 1):
                check_cancelled(cancel_check)
                p = point(i, j)
                add_grid_segment(p, point(i + 1, j))
                add_grid_segment(p, point(i, j + 1))
                add_grid_segment(p, point(i - 1, j + 1))
        return chain_segments_to_paths(contours)

    half = max(spacing * 0.5, 0.05)
    x_min = int(math.floor((min_x - half) / half)) - 1
    x_max = int(math.ceil((max_x + half) / half)) + 1
    y_min = int(math.floor((min_y - half) / half)) - 1
    y_max = int(math.ceil((max_y + half) / half)) + 1
    for j in range(y_min, y_max + 1):
        check_cancelled(cancel_check)
        y = j * half
        for i in range(x_min, x_max + 1):
            check_cancelled(cancel_check)
            x = i * half
            # Rhombic lattice: every vertex connects to the two vertices in the
            # next column. Adjacent diamonds share these vertices instead of
            # being stamped as isolated cells.
            add_grid_segment((x, y), (x + half, y + half))
            add_grid_segment((x, y), (x + half, y - half))
    return chain_segments_to_paths(contours)


def wave_region_contours(polygons, spacing, angle_deg=0.0, amplitude=None, wavelength=None, cancel_check=None):
    """Sinusoidal wave fill lines clipped to the region."""
    if spacing <= 0 or not polygons:
        return []
    if amplitude is None:
        amplitude = spacing * 0.42   # nearly-touching waves — clearly curved
    if wavelength is None:
        wavelength = spacing * 2.0   # longer wavelength = more obviously sinusoidal
    ang = math.radians(angle_deg)
    ca, sa = math.cos(ang), math.sin(ang)
    min_x, min_y, max_x, max_y = rotated_region_bounds(polygons, angle_deg)
    if max_y <= min_y:
        return []
    width = max_x - min_x + 4.0 * spacing
    steps_per_wave = 24   # smoother curves

    def world(x, y):
        return (x * ca - y * sa, x * sa + y * ca)

    contours = []
    y = math.floor((min_y - spacing) / spacing) * spacing
    row = 0
    while y <= max_y + spacing:
        check_cancelled(cancel_check)
        n_steps = max(4, int(width / max(wavelength, 1e-6) * steps_per_wave))
        phase = math.pi if row % 2 else 0.0
        points = [
            world(
                min_x - 2.0 * spacing + i * width / n_steps,
                y + amplitude * math.sin(2.0 * math.pi * (i / n_steps) * (width / wavelength) + phase),
            )
            for i in range(n_steps + 1)
        ]
        contours.extend(clip_polyline_to_region(points, polygons))
        y += spacing
        row += 1
    return contours


# Continuous adjacent sinusoids: how the tone-driven sine fill reads the
# rendered image. A row carries no ink below this darkness, so a gradient fades
# out instead of leaving a flat line running through its white end.
SINE_GRADIENT_INK_FLOOR = 0.04
# Samples per wavelength. 24 keeps a 2 x spacing wave visibly round without
# flooding the G-code with points.
SINE_GRADIENT_SAMPLES_PER_WAVE = 24


def sine_gradient_region_contours(
    bounds,
    darkness,
    spacing,
    angle_deg=0.0,
    amplitude_pct=50.0,
    density_pct=100.0,
    ink_floor=SINE_GRADIENT_INK_FLOOR,
    connect_rows=True,
    cancel_check=None,
):
    """Continuous adjacent sinusoids whose amplitude follows the local tone.

    This is the plotter-art gradient, the same idea as SquiggleDraw's
    brightness-driven sine rows: each sample's amplitude comes from the rendered
    darkness at that sample's row baseline, and the darkness also drives how
    fast the wave wiggles. A dark area therefore gets tall, tight squiggles and
    a light one gets flat, slow ones, so the tone reads as shape instead of as
    line density. ``density_pct`` is how much tone tightens the wiggle: 0 keeps
    one wavelength across the row, 100 makes the darkest areas wiggle twice as
    fast as the lightest, 400 five times. Rows are emitted in antiphase, so at
    full darkness the crest of one row just meets the trough of its neighbour
    instead of crossing it.

    ``bounds`` is ``(left, top, right, bottom)`` and ``darkness(x, y)`` returns
    ``0..1`` in that same frame. Rows run along the rotated x axis, so the
    caller never has to rotate the tone field itself.

    With ``connect_rows`` the end of one row is joined to the start of the next
    into a single pen-down serpentine. Rows whose joins pass over blank paper
    stay separate passes: there is no ink to hide a connector in, and drawing
    one there would leave a visible mark outside the artwork.
    """
    if darkness is None or spacing is None or float(spacing) <= 0.0:
        return []
    spacing = float(spacing)
    left, top, right, bottom = (float(value) for value in bounds)
    if right <= left or bottom <= top:
        return []
    amplitude = spacing * max(0.0, min(float(amplitude_pct), 100.0)) / 100.0
    density = max(0.0, float(density_pct)) / 100.0
    wavelength = spacing * 2.0
    wave_number = 2.0 * math.pi / max(wavelength, 1e-9)
    step = max(wavelength / float(SINE_GRADIENT_SAMPLES_PER_WAVE), 1e-6)
    floor = max(0.0, float(ink_floor))

    # Rotate about the bounds centre so the row arithmetic stays small and
    # independent of where the artwork sits on the bed.
    center_x = (left + right) * 0.5
    center_y = (top + bottom) * 0.5
    ang = math.radians(float(angle_deg))
    ca, sa = math.cos(ang), math.sin(ang)

    def to_local(x, y):
        dx, dy = x - center_x, y - center_y
        return (dx * ca + dy * sa, -dx * sa + dy * ca)

    def to_world(u, v):
        return (center_x + u * ca - v * sa, center_y + u * sa + v * ca)

    def tone_at(x, y):
        value = darkness(x, y)
        if value is None:
            return 0.0
        return max(0.0, min(float(value), 1.0))

    local = [to_local(x, y) for x, y in ((left, top), (right, top), (right, bottom), (left, bottom))]
    min_u = min(point[0] for point in local) - spacing
    max_u = max(point[0] for point in local) + spacing
    min_v = min(point[1] for point in local) - spacing
    max_v = max(point[1] for point in local) + spacing
    steps = max(2, int(math.ceil((max_u - min_u) / step)) + 1)
    du = (max_u - min_u) / steps

    runs_per_row = []
    row = 0
    v = math.floor(min_v / spacing) * spacing
    while v <= max_v:
        check_cancelled(cancel_check)
        # Accumulated phase, exactly as SquiggleDraw does it: the increment per
        # step is the local brightness, so dark paper wiggles faster instead of
        # just taller. Flat regions still get samples, which keeps the row one
        # continuous stroke instead of a chain of separate curves.
        phase = math.pi if row % 2 else 0.0
        phase = math.pi if row % 2 else 0.0
        runs = []
        current = []
        for index in range(steps + 1):
            check_cancelled(cancel_check)
            u = min_u + index * du
            base_x, base_y = to_world(u, v)
            value = tone_at(base_x, base_y)
            if value < floor:
                if len(current) >= 2:
                    runs.append(current)
                current = []
                continue
            phase += wave_number * (1.0 + density * value) * du
            offset = amplitude * value * math.sin(phase)
            current.append(to_world(u, v + offset))
        if len(current) >= 2:
            runs.append(current)
        runs_per_row.append(runs)
        v += spacing
        row += 1

    if not connect_rows:
        return [run for runs in runs_per_row for run in runs]

    # Serpentine: alternate the travel direction so the end of one row meets the
    # start of the next. A row that is blank end to end breaks the stroke where
    # the pen has to lift anyway.
    ordered = []
    for index, runs in enumerate(runs_per_row):
        if index % 2:
            ordered.extend(list(reversed([list(reversed(run)) for run in runs])))
        else:
            ordered.extend(runs)

    paths = []
    current = []
    for run in ordered:
        if current:
            previous = current[-1]
            gap = distance(previous, run[0])
            midpoint = ((previous[0] + run[0][0]) * 0.5, (previous[1] + run[0][1]) * 0.5)
            if gap > spacing * 2.0 or tone_at(midpoint[0], midpoint[1]) < floor:
                paths.append(current)
                current = []
        current.extend(run)
    if current:
        paths.append(current)
    return [path for path in paths if len(path) >= 2]


def gyroid_region_contours(polygons, spacing, angle_deg=0.0, cancel_check=None):
    """Gyroid-like 2D implicit infill clipped to the region.

    This follows the common slicer-style visual language: a continuous-looking
    sinusoidal lattice, not a pair of straight hatch families.
    """
    if spacing <= 0 or not polygons:
        return []
    ang = math.radians(angle_deg)
    ca, sa = math.cos(ang), math.sin(ang)
    min_x, min_y, max_x, max_y = rotated_region_bounds(polygons, angle_deg)
    if max_x <= min_x or max_y <= min_y:
        return []
    margin = spacing * 1.5
    min_x -= margin
    max_x += margin
    min_y -= margin
    max_y += margin
    cell = max(spacing / 6.0, 0.1)
    k = 2.0 * math.pi / max(spacing * 2.0, 1e-6)

    def field(x, y):
        return math.sin(x * k) * math.cos(y * k) + math.sin(y * k) * math.cos(x * k)

    def world(x, y):
        return (x * ca - y * sa, x * sa + y * ca)

    def interp(p0, v0, p1, v1):
        denom = v0 - v1
        t = 0.5 if abs(denom) < 1e-12 else max(0.0, min(1.0, v0 / denom))
        return (p0[0] + (p1[0] - p0[0]) * t, p0[1] + (p1[1] - p0[1]) * t)

    contours = []
    y = math.floor(min_y / cell) * cell
    while y < max_y:
        check_cancelled(cancel_check)
        x = math.floor(min_x / cell) * cell
        while x < max_x:
            check_cancelled(cancel_check)
            pts = [(x, y), (x + cell, y), (x + cell, y + cell), (x, y + cell)]
            vals = [field(px, py) for px, py in pts]
            crossings = []
            for i, j in ((0, 1), (1, 2), (2, 3), (3, 0)):
                vi, vj = vals[i], vals[j]
                if (vi <= 0.0 < vj) or (vj <= 0.0 < vi):
                    crossings.append(interp(pts[i], vi, pts[j], vj))
            if len(crossings) == 2:
                contours.extend(clip_segment_to_region(world(*crossings[0]), world(*crossings[1]), polygons))
            elif len(crossings) == 4:
                contours.extend(clip_segment_to_region(world(*crossings[0]), world(*crossings[1]), polygons))
                contours.extend(clip_segment_to_region(world(*crossings[2]), world(*crossings[3]), polygons))
            x += cell
        y += cell
    return contours


def _polygon_signed_area2(pts):
    n = len(pts)
    return sum(
        (pts[i][0] * pts[(i + 1) % n][1] - pts[(i + 1) % n][0] * pts[i][1])
        for i in range(n)
    )


def contour_inside_region(contour, polygons):
    if len(contour) < 2:
        return False
    checks = list(contour)
    checks.extend(((a[0] + b[0]) / 2.0, (a[1] + b[1]) / 2.0) for a, b in zip(contour, contour[1:]))
    return all(point_in_region(point, polygons) for point in checks)


def inset_polygon_simple(polygon, offset):
    """Inset a polygon by *offset* (positive = toward interior).

    Works accurately for convex polygons; concave polygons may produce
    self-intersections at sharp inward corners, which are left to the caller
    to detect via area collapse.
    """
    pts = polygon[:-1] if (len(polygon) > 1 and polygon[0] == polygon[-1]) else list(polygon)
    n = len(pts)
    if n < 3:
        return []
    area2 = _polygon_signed_area2(pts)
    winding = 1.0 if area2 > 0 else -1.0

    new_pts = []
    for i in range(n):
        a = pts[(i - 1) % n]
        b = pts[i]
        c = pts[(i + 1) % n]
        d1x, d1y = b[0] - a[0], b[1] - a[1]
        d2x, d2y = c[0] - b[0], c[1] - b[1]
        l1 = math.hypot(d1x, d1y)
        l2 = math.hypot(d2x, d2y)
        if l1 < 1e-9 or l2 < 1e-9:
            new_pts.append(b)
            continue
        # Inward unit normals
        n1x, n1y = -winding * d1y / l1,  winding * d1x / l1
        n2x, n2y = -winding * d2y / l2,  winding * d2x / l2
        # Bisector
        bx, by = n1x + n2x, n1y + n2y
        bl = math.hypot(bx, by)
        if bl < 1e-9:
            new_pts.append((b[0] + n1x * offset, b[1] + n1y * offset))
            continue
        dot = n1x * (bx / bl) + n1y * (by / bl)
        if abs(dot) < 1e-9:
            new_pts.append((b[0] + n1x * offset, b[1] + n1y * offset))
        else:
            d = offset / dot
            new_pts.append((b[0] + bx / bl * d, b[1] + by / bl * d))

    if len(new_pts) < 3:
        return []
    return new_pts + [new_pts[0]]


def concentric_region_contours(polygons, spacing, cancel_check=None):
    """Progressively inset each polygon ring, producing concentric contours."""
    if spacing <= 0 or not polygons:
        return []
    contours = []
    for polygon in polygons:
        check_cancelled(cancel_check)
        if len(polygon) < 3:
            continue
        outer = polygon[:-1] if (len(polygon) > 1 and polygon[0] == polygon[-1]) else list(polygon)
        if len(outer) < 3:
            continue
        outer_area2 = _polygon_signed_area2(outer)
        outer_sign = 1.0 if outer_area2 >= 0 else -1.0
        prev_abs = abs(outer_area2)
        current = list(polygon)
        if not contour_inside_region(current, polygons):
            continue
        for _ in range(500):
            check_cancelled(cancel_check)
            inset = inset_polygon_simple(current, spacing)
            if len(inset) < 3:
                break
            inner = inset[:-1] if inset[0] == inset[-1] else inset
            if len(inner) < 3:
                break
            area2 = _polygon_signed_area2(inner)
            abs_area2 = abs(area2)
            # Stop if polygon inverted (winding flipped) or area grew (diverging) or collapsed
            inner_sign = 1.0 if area2 >= 0 else -1.0
            if inner_sign != outer_sign or abs_area2 >= prev_abs or abs_area2 < spacing * spacing * 0.25:
                break
            if not contour_inside_region(inset, polygons):
                break
            prev_abs = abs_area2
            contours.append(inset)
            current = inset
    return contours


def _pattern_spacing(pattern, fill_spacing, pattern_sizes=None, triangle_size=0.0):
    value = 0.0
    if pattern_sizes:
        value = float(pattern_sizes.get(pattern, 0.0))
    elif pattern == "triangular":
        value = float(triangle_size)
    if value > 0.0:
        return max(value, 1e-6)
    fill_spacing = float(fill_spacing)
    if pattern in CELL_PATTERNS:
        return max(fill_spacing * CELL_SPACING_SCALE, 1e-6)
    return max(fill_spacing, 1e-6)


def _shading_bounds(polygons):
    min_x, min_y, max_x, max_y = rotated_region_bounds(polygons, 0.0)
    return (min_x, min_y, max_x, max_y)


def _shading_callbacks(polygons, darkness):
    tone = 0.0 if darkness is None else max(0.0, min(float(darkness), 1.0))
    inside = lambda x, y: point_in_region((x, y), polygons)
    dark = lambda x, y: tone
    return inside, dark


def stipple_region_contours(polygons, spacing, darkness, cancel_check=None, unit_per_mm=1.0, pen_diameter_mm=0.0):
    """Tone-driven stipple dots clipped to the filled region.

    ``unit_per_mm`` converts the on-paper dot size into the view units the
    fill is generated in (``1 / scale`` for the vector path), so a stipple dot
    keeps its physical size - and survives the sub-pen-width geometry filter -
    whatever the artwork's viewBox says.
    """
    if spacing <= 0.0 or not polygons:
        return []
    inside, dark = _shading_callbacks(polygons, darkness)
    points = stipple_points(
        _shading_bounds(polygons),
        inside,
        dark,
        spacing,
        cancel_check=cancel_check,
    )
    radius = stipple_mark_radius(pen_diameter_mm) * max(float(unit_per_mm), 0.0)
    segments = []
    for circle in dot_mark_contours(points, radius):
        segments.extend(clip_polyline_to_region(circle, polygons))
    # Clipping splits a closed dot into one two-point contour per edge, and the
    # paper-space filter would then drop each edge as a sliver. Chain the edges
    # back so every dot stays a single closed contour of its full circumference.
    return chain_segments_to_paths(segments)


def halftone_region_contours(polygons, spacing, darkness, angle_deg=0.0, cancel_check=None):
    """Variable-radius halftone dots clipped to the filled region."""
    if spacing <= 0.0 or not polygons:
        return []
    inside, dark = _shading_callbacks(polygons, darkness)
    circles = halftone_contours(
        _shading_bounds(polygons),
        inside,
        dark,
        spacing,
        angle_deg,
        cancel_check=cancel_check,
    )
    segments = []
    for circle in circles:
        segments.extend(clip_polyline_to_region(circle, polygons))
    return chain_segments_to_paths(segments)


def tsp_region_contours(polygons, spacing, darkness, cancel_check=None):
    """Single-line stipple path clipped to the filled region."""
    if spacing <= 0.0 or not polygons:
        return []
    inside, dark = _shading_callbacks(polygons, darkness)
    points = stipple_points(
        _shading_bounds(polygons),
        inside,
        dark,
        spacing,
        cancel_check=cancel_check,
    )
    line = greedy_single_line(points, cell=spacing, cancel_check=cancel_check)
    if len(line) < 2:
        return []
    return chain_segments_to_paths(clip_polyline_to_region(line, polygons))


def fill_pattern_contours(polygon, spacing, base_angle, levels, angle_step, darkness, pattern, triangle_size=0.0, pattern_sizes=None, cancel_check=None, fill_inset=0.0, gradient_amplitude_pct=50.0, gradient_density_pct=100.0, unit_per_mm=1.0, pen_diameter_mm=0.0):
    return fill_region_pattern_contours([polygon], spacing, base_angle, levels, angle_step, darkness, pattern, triangle_size, pattern_sizes, cancel_check, fill_inset, gradient_amplitude_pct, gradient_density_pct, unit_per_mm, pen_diameter_mm)


def fill_region_pattern_contours(polygons, spacing, base_angle, levels, angle_step, darkness, pattern, triangle_size=0.0, pattern_sizes=None, cancel_check=None, fill_inset=0.0, gradient_amplitude_pct=50.0, gradient_density_pct=100.0, unit_per_mm=1.0, pen_diameter_mm=0.0):
    check_cancelled(cancel_check)
    pattern = normalized_hatch_pattern(pattern)
    # Photo-shading patterns read tone directly (density, dot size, or a single
    # connected path), so like `sine_gradient` they are drawn at the requested
    # spacing and ignore `Shade levels` instead of counting tone twice.
    if pattern == "stipple":
        return stipple_region_contours(
            polygons,
            _pattern_spacing(pattern, spacing, pattern_sizes, triangle_size),
            darkness,
            cancel_check,
            unit_per_mm,
            pen_diameter_mm,
        )
    if pattern == "halftone":
        return halftone_region_contours(
            polygons,
            _pattern_spacing(pattern, spacing, pattern_sizes, triangle_size),
            darkness,
            base_angle,
            cancel_check,
        )
    if pattern == "tsp":
        return tsp_region_contours(
            polygons,
            _pattern_spacing(pattern, spacing, pattern_sizes, triangle_size),
            darkness,
            cancel_check,
        )
    fill_spacing = density_spacing(spacing, levels, darkness)
    if fill_spacing is None:
        return []
    # The lattice is clipped to the fill region exactly as drawn. The bleed
    # margin is applied later, by pulling back the ends the clip creates, rather
    # than by offsetting each subpath: offsetting independently cannot preserve
    # even-odd parity once subpaths overlap, and a bitmap trace is made of
    # thousands of overlapping subpaths. See the 2026-09-27 change note.
    if pattern == "dots":
        return mark_grid_contours(polygons, _pattern_spacing(pattern, fill_spacing, pattern_sizes, triangle_size), base_angle, "dots", cancel_check)
    if pattern in ("circles", "diamonds", "hexagonal", "triangular"):
        pattern_spacing = _pattern_spacing(pattern, fill_spacing, pattern_sizes, triangle_size)
        return tile_shape_contours(polygons, pattern_spacing, base_angle, pattern, cancel_check)
    if pattern == "waves":
        # `wave_region_contours` clips one segment at a time, so a row arrives
        # as a long run of two-point contours. Chain them back into continuous
        # sine rows: the pen draws a wave, not a row of dots, and one row costs
        # one M3/M5 cycle instead of one per sample.
        return chain_segments_to_paths(
            wave_region_contours(
                polygons,
                _pattern_spacing(pattern, fill_spacing, pattern_sizes, triangle_size),
                base_angle,
                cancel_check=cancel_check,
            )
        )
    # In vector mode the tone is the element's own fill (or stroke) darkness, so
    # the wave amplitude follows it exactly as the rendered tone does in the
    # image-tone path: a black region gets crests, a pale one gets flat lines.
    # Spacing is *not* darkened here - for this pattern tone is amplitude, and
    # letting `Shade levels` also tighten the pitch would count it twice.
    if pattern == "sine_gradient":
        pitch = _pattern_spacing(pattern, spacing, pattern_sizes, triangle_size)
        tone = 0.0 if darkness is None else max(0.0, min(float(darkness), 1.0))
        amplitude = pitch * max(0.0, min(float(gradient_amplitude_pct), 100.0)) / 100.0 * tone
        # One tone for the whole element, so the pitch stays the base wavelength
        # and the density percentage shortens it by the same rule as the
        # image-tone path.
        density = max(0.0, float(gradient_density_pct)) / 100.0
        wavelength = pitch * 2.0 / (1.0 + density * tone)
        return chain_segments_to_paths(
            wave_region_contours(
                polygons,
                pitch,
                base_angle,
                amplitude=amplitude,
                wavelength=wavelength,
                cancel_check=cancel_check,
            )
        )
    if pattern == "gyroid":
        return gyroid_region_contours(polygons, _pattern_spacing(pattern, fill_spacing, pattern_sizes, triangle_size), base_angle, cancel_check)
    if pattern == "concentric":
        return concentric_region_contours(polygons, _pattern_spacing(pattern, fill_spacing, pattern_sizes, triangle_size), cancel_check)
    if pattern == "cubic":
        # Isometric cube grid: three line families at 30°, 90°, 150°
        cubic_spacing = _pattern_spacing(pattern, fill_spacing, pattern_sizes, triangle_size)
        out = []
        for angle in (base_angle + 30.0, base_angle + 90.0, base_angle + 150.0):
            check_cancelled(cancel_check)
            out.extend(line_region_contours(polygons, cubic_spacing, angle, cancel_check, fill_inset))
        return out
    angles = pattern_angles(base_angle, levels, angle_step, darkness, pattern)
    out = []
    for angle in angles:
        check_cancelled(cancel_check)
        out.extend(line_region_contours(polygons, fill_spacing, angle, cancel_check, fill_inset))
    return out


def hatch_polygon(polygon, spacing, angle_deg=0.0):
    if spacing <= 0 or len(polygon) < 3:
        return []
    ang = math.radians(angle_deg)
    cs, sn = math.cos(-ang), math.sin(-ang)
    rot = [(x * cs - y * sn, x * sn + y * cs) for x, y in polygon]
    if (rot[0][0] - rot[-1][0]) ** 2 + (rot[0][1] - rot[-1][1]) ** 2 > 1e-9:
        rot.append(rot[0])
    min_y = min(p[1] for p in rot)
    max_y = max(p[1] for p in rot)
    if max_y - min_y < spacing:
        return []
    ca, sa = math.cos(ang), math.sin(ang)
    n = len(rot)
    runs = []
    y = min_y + spacing * 0.5
    while y < max_y:
        xs = []
        for i in range(n - 1):
            y1, y2 = rot[i][1], rot[i + 1][1]
            if (y1 <= y < y2) or (y2 <= y < y1):
                t = (y - y1) / (y2 - y1)
                xs.append(rot[i][0] + t * (rot[i + 1][0] - rot[i][0]))
        xs.sort()
        pairs = []
        for k in range(0, len(xs) - 1, 2):
            pairs.append((xs[k], xs[k + 1]))
        if pairs:
            runs.append((y, pairs))
        y += spacing
    if not runs:
        return []

    def world(x, y):
        return (x * ca - y * sa, x * sa + y * ca)

    chains = []
    for run_index, (y, pairs) in enumerate(runs):
        reversed_pass = (run_index % 2) == 1
        ordered_pairs = list(reversed(pairs)) if reversed_pass else pairs
        for x_left, x_right in ordered_pairs:
            if reversed_pass:
                start_x, end_x = x_right, x_left
            else:
                start_x, end_x = x_left, x_right
            start_pt = world(start_x, y)
            end_pt = world(end_x, y)
            chains.append([start_pt, end_pt])
    return chains


def stroke_expanded_contours(contours, width):
    if width <= 0:
        return contours
    expanded = []
    half = width / 2.0
    for contour in contours:
        if len(contour) < 2:
            continue
        if distance(contour[0], contour[-1]) <= 1e-9:
            expanded.append(contour)
            continue
        for a, b in zip(contour, contour[1:]):
            dx, dy = b[0] - a[0], b[1] - a[1]
            length = math.hypot(dx, dy)
            if length <= 1e-9:
                continue
            nx, ny = -dy / length * half, dx / length * half
            expanded.append([
                (a[0] + nx, a[1] + ny),
                (b[0] + nx, b[1] + ny),
                (b[0] - nx, b[1] - ny),
                (a[0] - nx, a[1] - ny),
                (a[0] + nx, a[1] + ny),
            ])
    return expanded


def offset_polyline(points, offset):
    """Return *points* shifted perpendicular to the local tangent by *offset*.

    The tangent at each vertex is the direction from its predecessor to its
    successor, so endpoints use the single adjacent segment and interior
    vertices use the average direction. This is a per-vertex offset (no miter
    limit), which is smooth enough for pen-fill passes along a stroke but is
    not a robust polygon offset for sharp corners.
    """
    if not points:
        return []
    if abs(offset) < 1e-9 or len(points) < 2:
        return list(points)
    out = []
    for i in range(len(points)):
        prev = points[i - 1] if i > 0 else points[i]
        nxt = points[i + 1] if i < len(points) - 1 else points[i]
        dx = nxt[0] - prev[0]
        dy = nxt[1] - prev[1]
        length = math.hypot(dx, dy)
        if length < 1e-9:
            out.append((points[i][0], points[i][1]))
            continue
        nx = -dy / length
        ny = dx / length
        out.append((points[i][0] + nx * offset, points[i][1] + ny * offset))
    return out


def stroke_fill_contours(contours, width, pen_diameter):
    """Fill each stroked polyline with parallel passes spaced *pen_diameter* apart.

    A pen draws a line of its own diameter, so a stroke wider than that is
    rendered by tracing parallel copies of its centerline, offset perpendicular
    to the path and covering the stroke width. Returns the pass contours (each a
    single line, so they plan and draw like normal strokes), or the originals
    when the stroke is not wide enough to need more than one pass.
    """
    if width <= 0 or pen_diameter <= 0 or not contours:
        return contours
    passes = max(1, int(math.ceil(width / pen_diameter)))
    if passes <= 1:
        return contours
    filled = []
    for contour in contours:
        if len(contour) < 2:
            continue
        half_span = (passes - 1) * pen_diameter / 2.0
        for i in range(passes):
            offset = -half_span + i * pen_diameter
            shifted = offset_polyline(contour, offset)
            if len(shifted) >= 2:
                filled.append(shifted)
    return filled


def distance(a, b):
    return math.hypot(b[0] - a[0], b[1] - a[1])


def cubic(p0, p1, p2, p3, t):
    u = 1.0 - t
    return (u**3*p0[0] + 3*u*u*t*p1[0] + 3*u*t*t*p2[0] + t**3*p3[0], u**3*p0[1] + 3*u*u*t*p1[1] + 3*u*t*t*p2[1] + t**3*p3[1])


def quad(p0, p1, p2, t):
    u = 1.0 - t
    return (u*u*p0[0] + 2*u*t*p1[0] + t*t*p2[0], u*u*p0[1] + 2*u*t*p1[1] + t*t*p2[1])


def add_curve(points, fn, start, end, tolerance):
    rough = distance(start, end)
    steps = max(8, min(240, int(rough / max(tolerance, 0.01)) + 8))
    for i in range(1, steps + 1):
        points.append(fn(i / steps))


def path_to_contours(d, tolerance, cancel_check=None):
    tokens = COMMAND_RE.findall(d or "")
    contours, points = [], []
    i, cmd = 0, None
    current = start = (0.0, 0.0)
    last_cubic = last_quad = None

    def is_cmd(idx):
        return idx < len(tokens) and re.match(r"^[A-Za-z]$", tokens[idx])

    def read_float():
        nonlocal i
        check_cancelled(cancel_check)
        value = float(tokens[i])
        i += 1
        return value

    def absolutize(p, absolute):
        return p if absolute else (current[0] + p[0], current[1] + p[1])

    def line_to(p):
        nonlocal current
        points.append(p)
        current = p

    while i < len(tokens):
        check_cancelled(cancel_check)
        if is_cmd(i):
            cmd = tokens[i]
            i += 1
        if cmd is None:
            break
        absolute = cmd.isupper()
        op = cmd.upper()
        if op == "M":
            first = True
            while i + 1 < len(tokens) and not is_cmd(i):
                p = absolutize((read_float(), read_float()), absolute)
                if first:
                    if len(points) > 1:
                        contours.append(points)
                    points = [p]
                    current = start = p
                    first = False
                else:
                    line_to(p)
            cmd = "L" if absolute else "l"
        elif op == "L":
            while i + 1 < len(tokens) and not is_cmd(i):
                line_to(absolutize((read_float(), read_float()), absolute))
        elif op == "H":
            while i < len(tokens) and not is_cmd(i):
                x = read_float()
                line_to((x, current[1]) if absolute else (current[0] + x, current[1]))
        elif op == "V":
            while i < len(tokens) and not is_cmd(i):
                y = read_float()
                line_to((current[0], y) if absolute else (current[0], current[1] + y))
        elif op == "C":
            while i + 5 < len(tokens) and not is_cmd(i):
                c1 = absolutize((read_float(), read_float()), absolute)
                c2 = absolutize((read_float(), read_float()), absolute)
                p = absolutize((read_float(), read_float()), absolute)
                p0 = current
                add_curve(points, lambda t, p0=p0, c1=c1, c2=c2, p=p: cubic(p0, c1, c2, p, t), p0, p, tolerance)
                current, last_cubic, last_quad = p, c2, None
        elif op == "S":
            while i + 3 < len(tokens) and not is_cmd(i):
                c1 = (2*current[0] - last_cubic[0], 2*current[1] - last_cubic[1]) if last_cubic else current
                c2 = absolutize((read_float(), read_float()), absolute)
                p = absolutize((read_float(), read_float()), absolute)
                p0 = current
                add_curve(points, lambda t, p0=p0, c1=c1, c2=c2, p=p: cubic(p0, c1, c2, p, t), p0, p, tolerance)
                current, last_cubic, last_quad = p, c2, None
        elif op == "Q":
            while i + 3 < len(tokens) and not is_cmd(i):
                c = absolutize((read_float(), read_float()), absolute)
                p = absolutize((read_float(), read_float()), absolute)
                p0 = current
                add_curve(points, lambda t, p0=p0, c=c, p=p: quad(p0, c, p, t), p0, p, tolerance)
                current, last_quad, last_cubic = p, c, None
        elif op == "T":
            while i + 1 < len(tokens) and not is_cmd(i):
                c = (2*current[0] - last_quad[0], 2*current[1] - last_quad[1]) if last_quad else current
                p = absolutize((read_float(), read_float()), absolute)
                p0 = current
                add_curve(points, lambda t, p0=p0, c=c, p=p: quad(p0, c, p, t), p0, p, tolerance)
                current, last_quad, last_cubic = p, c, None
        elif op == "A":
            while i + 6 < len(tokens) and not is_cmd(i):
                read_float(); read_float(); read_float(); read_float(); read_float()
                line_to(absolutize((read_float(), read_float()), absolute))
                last_cubic = last_quad = None
        elif op == "Z":
            if points and distance(points[-1], start) > 1e-9:
                points.append(start)
            if len(points) > 1:
                contours.append(points)
            points = []
            current = start
            last_cubic = last_quad = None
        else:
            break
        if op not in ("C", "S"):
            last_cubic = None
        if op not in ("Q", "T"):
            last_quad = None
    if len(points) > 1:
        contours.append(points)
    return contours


def closed_outline_regions(contours, tolerance):
    """Polygons enclosed by an element's closed outline loops.

    Single-pen line art declares `fill="none"`, so the SVG itself carries no
    filled region to hatch. The area a pen *can* fill is the one bounded by a
    closed outline, so those loops become the fill region for that element.
    Open subpaths are ignored: there is no bounded interior to fill, and
    guessing one would bleed fill across the artwork (the Calders and F15
    plotter exports are built from open segments).
    """
    close_tol = max(float(tolerance) * 2.0, 1e-6)
    min_area2 = 2.0 * close_tol * close_tol
    polygons = []
    for contour in contours:
        if len(contour) < 4:
            continue
        if distance(contour[0], contour[-1]) > close_tol:
            continue
        polygon = list(contour)
        polygon[-1] = polygon[0]
        if abs(_polygon_signed_area2(polygon[:-1])) < min_area2:
            continue
        polygons.append(polygon)
    return polygons


def element_contours(element, tolerance, hatch_spacing=0.0, hatch_angle=0.0, hatch_pattern="crosshatch", shade_levels=1, shade_angle_step=90.0, expand_strokes=True, triangle_size=0.0, pattern_sizes=None, cancel_check=None, fill_inset=0.0, fill_wide_strokes=False, stroke_fill_ratio=2.0, pen_diameter=0.0, inherited=None, stats=None, gradient_amplitude_pct=50.0, gradient_density_pct=100.0, unit_per_mm=1.0):
    check_cancelled(cancel_check)
    # Skip elements that are invisible in a single-pen plot (white/transparent
    # fill and stroke). A white knockout/background path would otherwise be
    # traced as pen strokes and its often-large geometry still costs parse and
    # plan time.
    if not _element_is_visible(element, inherited):
        return []
    tag = strip_ns(element.tag)
    contours = []
    if tag == "path":
        contours = path_to_contours(element.get("d"), tolerance, cancel_check)
    elif tag == "line":
        contours = [[(parse_length(element.get("x1")), parse_length(element.get("y1"))), (parse_length(element.get("x2")), parse_length(element.get("y2")))]]
    elif tag in ("polyline", "polygon"):
        pts = parse_points(element.get("points"))
        if tag == "polygon" and pts and pts[0] != pts[-1]:
            pts.append(pts[0])
        contours = [pts] if len(pts) > 1 else []
    elif tag == "rect":
        x, y = parse_length(element.get("x")), parse_length(element.get("y"))
        w, h = parse_length(element.get("width")), parse_length(element.get("height"))
        contours = [[(x, y), (x + w, y), (x + w, y + h), (x, y + h), (x, y)]] if w > 0 and h > 0 else []
    elif tag in ("circle", "ellipse"):
        cx, cy = parse_length(element.get("cx")), parse_length(element.get("cy"))
        rx = parse_length(element.get("r") if tag == "circle" else element.get("rx"))
        ry = parse_length(element.get("r") if tag == "circle" else element.get("ry"))
        if rx > 0 and ry > 0:
            steps = max(24, min(360, int(2 * math.pi * max(rx, ry) / max(tolerance, 0.01))))
            contours = [[(cx + rx * math.cos(2 * math.pi * n / steps), cy + ry * math.sin(2 * math.pi * n / steps)) for n in range(steps + 1)]]
    fill_lines = []
    if hatch_spacing > 0:
        fill_polygons = []
        if has_visible_fill(element, inherited):
            # An SVG fill implicitly closes an open subpath, but this plotter
            # draws only the ink the file contains: that implicit chord is a
            # boundary the pen never draws, so the fill reads as marks floating
            # in blank space. Require a genuinely closed loop, exactly like the
            # stroke-only branch below.
            fill_polygons = closed_outline_regions(contours, tolerance)
            darkness = fill_darkness(element, inherited)
        elif has_visible_stroke(element, inherited):
            # Stroke-only artwork: fill the interiors the outlines enclose.
            fill_polygons = closed_outline_regions(contours, tolerance)
            darkness = stroke_darkness(element, inherited)
        if fill_polygons:
            fill_lines.extend(fill_region_pattern_contours(fill_polygons, hatch_spacing, hatch_angle, shade_levels, shade_angle_step, darkness, hatch_pattern, triangle_size, pattern_sizes, cancel_check, fill_inset, gradient_amplitude_pct, gradient_density_pct, unit_per_mm, pen_diameter))
            if stats is not None:
                stats["fill_contours"] = stats.get("fill_contours", 0) + len(fill_lines)
    if has_visible_stroke(element, inherited):
        width = stroke_width(element, inherited)
        if fill_wide_strokes:
            # This mode owns stroke rendering end to end: a stroke wide enough to
            # need more than one pass is filled, and every thinner stroke stays a
            # single centerline. It deliberately supersedes expand_strokes, which
            # would otherwise outline exactly the thin strokes this mode exists
            # to keep as one pass.
            if pen_diameter > 0 and width >= stroke_fill_ratio * pen_diameter:
                contours = stroke_fill_contours(contours, width, pen_diameter)
        elif expand_strokes:
            contours = stroke_expanded_contours(contours, width)
    return contours + [FillTrail(trail) for trail in fill_lines]


def parse_svg_geometry(svg_path, tolerance, flip_y, hatch_spacing=0.0, hatch_angle=0.0, hatch_pattern="crosshatch", shade_levels=1, shade_angle_step=90.0, expand_strokes=True, triangle_size=0.0, pattern_sizes=None, cancel_check=None, scale=1.0, fill_wide_strokes=False, stroke_fill_ratio=2.0, pen_diameter=0.0, stats=None, gradient_amplitude_pct=50.0, gradient_density_pct=100.0):
    check_cancelled(cancel_check)
    # When the artwork is scaled down, generate the fill at the coarser SVG-space
    # spacing that matches the final on-paper density, instead of building the
    # lattice at full source resolution and shrinking it afterward. This keeps the
    # on-paper fill spacing constant and produces proportionally fewer contours
    # (scale^2 fewer) for small scales, which is the dominant preview cost.
    coarsen = 1.0 / scale if 0.0 < scale < 1.0 else 1.0
    tolerance = float(tolerance) * coarsen
    hatch_spacing = float(hatch_spacing) * coarsen
    triangle_size = float(triangle_size) * coarsen
    if pattern_sizes:
        pattern_sizes = {pattern: float(value) * coarsen for pattern, value in pattern_sizes.items()}
    fill_inset = FILL_INSET_MM * coarsen
    tree = ET.parse(svg_path)
    root = tree.getroot()
    height = parse_length(root.get("height"), 0.0)
    view_box_height = 0.0
    view_box = root.get("viewBox")
    if view_box:
        nums = [float(x) for x in NUMBER_RE.findall(view_box)]
        if len(nums) == 4:
            view_box_height = nums[3]
            if not height:
                height = nums[3]

    id_map = {node.get("id"): node for node in root.iter() if node.get("id")}
    contours = []

    def walk(node, matrix, style, referenced=False, seen=None):
        check_cancelled(cancel_check)
        seen = seen or set()
        tag = strip_ns(node.tag)
        if tag in ("defs", "symbol") and not referenced:
            return
        if style_hidden(node, style):
            return
        combined = matrix @ parse_transform(node.get("transform"))
        # Resolve this element's style once, then hand it to both the element
        # itself and its children so inherited presentation values behave the
        # way an SVG renderer applies them.
        resolved = inherited_style(style, node)
        if tag == "use":
            href = use_href(node)
            if href and href.startswith("#"):
                target_id = href[1:]
                target = id_map.get(target_id)
                if target is not None and target_id not in seen:
                    walk(target, combined @ Matrix(e=parse_length(node.get("x")), f=parse_length(node.get("y"))), resolved, True, seen | {target_id})
            return
        for contour in element_contours(node, tolerance, hatch_spacing, hatch_angle, hatch_pattern, shade_levels, shade_angle_step, expand_strokes, triangle_size, pattern_sizes, cancel_check, fill_inset, fill_wide_strokes, stroke_fill_ratio, pen_diameter, resolved, stats, gradient_amplitude_pct, gradient_density_pct, unit_per_mm=coarsen):
            check_cancelled(cancel_check)
            contours.append(retag_contour(contour, [combined.apply(x, y) for x, y in contour]))
        for child in list(node):
            walk(child, combined, resolved, referenced, seen)

    walk(root, Matrix(), {})
    if flip_y:
        source_height = view_box_height or height or max((y for contour in contours for _, y in contour), default=0.0)
        contours = [retag_contour(contour, [(x, source_height - y) for x, y in contour]) for contour in contours]
    return contours


def apply_geometry_settings(contours, settings):
    contours = [retag_contour(contour, [(x * settings.scale, y * settings.scale) for x, y in contour]) for contour in contours]
    # In on-paper space, drop sub-pen-width fragments (clipped infill slivers
    # and trace specks) that only add an M3/M5 "dot" with no visible value.
    contours = [contour for contour in contours if sum(distance(a, b) for a, b in zip(contour, contour[1:])) >= MIN_FILL_SEGMENT_LENGTH]
    if getattr(settings, "compensate_pen_width", True):
        contours = compensate_physical_pen_width(contours, settings.pen_diameter_mm)
    return contours


def read_svg(svg_path, settings):
    contours = parse_svg_geometry(
        svg_path,
        settings.tolerance,
        settings.flip_y,
        float(getattr(settings, "hatch_spacing_mm", 0.0)),
        float(getattr(settings, "hatch_angle_deg", 0.0)),
        str(getattr(settings, "hatch_pattern", "crosshatch")),
        int(getattr(settings, "shade_levels", 1)),
        float(getattr(settings, "shade_angle_step_deg", 90.0)),
        bool(getattr(settings, "expand_strokes", False)),
        float(getattr(settings, "triangle_size_mm", 0.0)),
        pattern_size_values(settings),
        None,
        float(getattr(settings, "scale", 1.0)),
        fill_wide_strokes=bool(getattr(settings, "fill_wide_strokes", False)),
        stroke_fill_ratio=float(getattr(settings, "stroke_fill_ratio", 2.0)),
        pen_diameter=float(getattr(settings, "pen_diameter_mm", 0.0)),
        gradient_amplitude_pct=float(getattr(settings, "gradient_wave_amplitude_pct", 50.0)),
        gradient_density_pct=float(getattr(settings, "gradient_wave_density_pct", 100.0)),
    )
    return apply_geometry_settings(contours, settings)


def contour_bounds(contours):
    pts = [point for contour in contours for point in contour]
    if not pts:
        return (0.0, 0.0, 0.0, 0.0)
    min_x = min(x for x, _ in pts)
    max_x = max(x for x, _ in pts)
    min_y = min(y for _, y in pts)
    max_y = max(y for _, y in pts)
    return min_x, min_y, max_x, max_y


# Artwork is placed by centering its bounding box on the bed center, so the
# radius that decides whether it fits the drawable circle is measured from that
# same box center, not from a point the artwork happens to contain.
def artwork_radius(contours):
    """Largest distance from the artwork's bounding-box center to any point."""
    if not contours:
        return 0.0
    min_x, min_y, max_x, max_y = contour_bounds(contours)
    center_x = (min_x + max_x) / 2.0
    center_y = (min_y + max_y) / 2.0
    return max(
        math.hypot(x - center_x, y - center_y)
        for contour in contours
        for x, y in contour
    )


def artwork_span(contours):
    """Artwork bounding-box size ``(width, height)`` at the current scale."""
    if not contours:
        return (0.0, 0.0)
    min_x, min_y, max_x, max_y = contour_bounds(contours)
    return (max_x - min_x, max_y - min_y)


def fit_scale_to_radius(contours, target_radius, margin=0.98):
    """Scale factor that sizes already-scaled *contours* to *target_radius*.

    This is the "fit inside" target: every point of the artwork ends up at
    ``target_radius * margin`` from the bed center, so nothing is clipped and the
    bounding-box corners land on the ring. It sizes in both directions - artwork
    smaller than the target is enlarged - so callers should treat the result as a
    size, not a cap. ``margin`` keeps the outermost drawn move just inside the
    limit rather than exactly on it.
    """
    target_radius = float(target_radius)
    margin = float(margin)
    if target_radius <= 0.0 or margin <= 0.0:
        return 1.0
    radius = artwork_radius(contours)
    if radius <= 0.0:
        return 1.0
    return target_radius * margin / radius


def fit_scale_to_span(contours, target_span, margin=0.98):
    """Scale factor that makes the artwork's bounding box span *target_span*.

    This is the "fill the bed" fit: the longer bounding-box side is placed on
    the drawable diameter, so the box edges touch the drawable circle and its
    four corners fall outside it. Unlike `fit_scale_to_radius` this sizes to the
    target in both directions - artwork smaller than the bed grows to fill it -
    and returns ``1.0`` only when the size is unknown.
    """
    target_span = float(target_span)
    margin = float(margin)
    if target_span <= 0.0 or margin <= 0.0:
        return 1.0
    width, height = artwork_span(contours)
    longest = max(width, height)
    if longest <= 0.0:
        return 1.0
    return target_span * margin / longest


def compensate_physical_pen_width(contours, pen_diameter):
    pen_diameter = max(float(pen_diameter), 0.0)
    if pen_diameter <= 0 or not contours:
        return contours
    min_x, min_y, max_x, max_y = contour_bounds(contours)
    span_x = max_x - min_x
    span_y = max_y - min_y
    if span_x <= pen_diameter and span_y <= pen_diameter:
        return contours
    center_x = (min_x + max_x) / 2.0
    center_y = (min_y + max_y) / 2.0
    sx = max((span_x - pen_diameter) / span_x, 0.0) if span_x > pen_diameter else 1.0
    sy = max((span_y - pen_diameter) / span_y, 0.0) if span_y > pen_diameter else 1.0
    # Preserve lattice angles and circular features. The old independent X/Y
    # shrink distorted equilateral/hex patterns whenever the artwork bbox was
    # not square.
    scale = min(sx, sy)
    return [
        retag_contour(contour, [(center_x + (x - center_x) * scale, center_y + (y - center_y) * scale) for x, y in contour])
        for contour in contours
    ]


def filtered_contour(contour):
    out = []
    for point in contour:
        if not out or distance(out[-1], point) > 1e-6:
            out.append(point)
    return retag_contour(contour, out)


def format_float(value):
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return text if text else "0"


def unwrap_angle(angle, previous):
    if previous is None:
        return angle
    while angle - previous > 180.0:
        angle -= 360.0
    while angle - previous < -180.0:
        angle += 360.0
    return angle



def contour_center(contours):
    pts = [point for contour in contours for point in contour]
    if not pts:
        return (0.0, 0.0)
    min_x = min(x for x, _ in pts)
    max_x = max(x for x, _ in pts)
    min_y = min(y for _, y in pts)
    max_y = max(y for _, y in pts)
    return ((min_x + max_x) / 2.0, (min_y + max_y) / 2.0)


def clip_segment_to_circle(a, b, center, radius):
    cx, cy = center
    ax, ay = a[0] - cx, a[1] - cy
    bx, by = b[0] - cx, b[1] - cy
    r2 = radius * radius
    a_in = ax * ax + ay * ay <= r2
    b_in = bx * bx + by * by <= r2
    if a_in and b_in:
        return a, b
    dx = bx - ax
    dy = by - ay
    A = dx * dx + dy * dy
    if A < 1e-18:
        return None
    B = 2.0 * (ax * dx + ay * dy)
    C = ax * ax + ay * ay - r2
    disc = B * B - 4.0 * A * C
    if disc < 0:
        return None
    sq = math.sqrt(disc)
    t1 = (-B - sq) / (2.0 * A)
    t2 = (-B + sq) / (2.0 * A)
    t_lo = max(0.0, min(t1, t2))
    t_hi = min(1.0, max(t1, t2))
    if t_hi <= t_lo:
        return None
    p_lo = (a[0] + t_lo * (b[0] - a[0]), a[1] + t_lo * (b[1] - a[1]))
    p_hi = (a[0] + t_hi * (b[0] - a[0]), a[1] + t_hi * (b[1] - a[1]))
    if a_in:
        return a, p_hi
    if b_in:
        return p_lo, b
    return p_lo, p_hi


def clip_contours_to_bed(contours, center, radius, cancel_check=None):
    if radius <= 0 or not contours:
        return list(contours)
    cx, cy = center
    r2 = radius * radius
    tol2 = max(radius * 1e-7, 1e-9) ** 2
    out = []
    for contour in contours:
        check_cancelled(cancel_check)
        if len(contour) < 2:
            continue
        current = []
        prev = contour[0]
        if (prev[0] - cx) ** 2 + (prev[1] - cy) ** 2 <= r2:
            current = [prev]
        for point in contour[1:]:
            check_cancelled(cancel_check)
            clipped = clip_segment_to_circle(prev, point, center, radius)
            point_in = (point[0] - cx) ** 2 + (point[1] - cy) ** 2 <= r2
            if clipped is None:
                if len(current) >= 2:
                    out.append(retag_contour(contour, current))
                current = []
            else:
                cl_a, cl_b = clipped
                if not current:
                    current = [cl_a, cl_b]
                else:
                    last = current[-1]
                    if (cl_a[0] - last[0]) ** 2 + (cl_a[1] - last[1]) ** 2 > tol2:
                        if len(current) >= 2:
                            out.append(retag_contour(contour, current))
                        current = [cl_a, cl_b]
                    else:
                        current.append(cl_b)
                if not point_in:
                    if len(current) >= 2:
                        out.append(retag_contour(contour, current))
                    current = []
            prev = point
        if len(current) >= 2:
            out.append(retag_contour(contour, current))
    return out
