import math
import re
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import converter_core as converter
import converter_core.gcode as gcode_module
from converter_core import kinematics


class RadiusAwareThetaFeedTests(unittest.TestCase):
    CENTER = (0.0, 0.0)

    def settings(self, **kwargs):
        defaults = {
            "feed_rate": 1200.0,
            "theta_tangential_speed_mm_min": 1200.0,
            "theta_controller_limits": converter.ThetaControllerLimits(
                max_rate_deg_min=1_000_000.0,
                max_acceleration_deg_s2=1_000_000_000.0,
            ),
        }
        defaults.update(kwargs)
        return converter.Settings(**defaults)

    def plan_at_radius(self, radius, motor_delta=100.0, **kwargs):
        return converter.plan_radius_aware_draw_feed(
            (radius, 0.0),
            (radius, 0.0),
            self.CENTER,
            0.0,
            motor_delta,
            self.settings(**kwargs),
        )

    def test_required_a_rate_is_inverse_to_radius(self):
        inner = self.plan_at_radius(50.0)
        outer = self.plan_at_radius(100.0)

        self.assertAlmostEqual(inner["a_rate_deg_min"], outer["a_rate_deg_min"] * 2.0)
        self.assertAlmostEqual(inner["tangential_speed_mm_min"], 1200.0)
        self.assertAlmostEqual(outer["tangential_speed_mm_min"], 1200.0)

    def test_tangential_speed_setting_is_loaded_from_the_ui_value(self):
        settings = converter.settings_from_values(
            {"theta_tangential_speed_mm_min": "725.5"},
            {},
        )

        self.assertEqual(settings.theta_tangential_speed_mm_min, 725.5)

    def test_motion_estimate_calibration_uses_the_m06_measurement(self):
        self.assertAlmostEqual(
            converter.calibrated_motion_seconds(160.58),
            75.05,
            places=6,
        )
        with self.assertRaises(ValueError):
            converter.calibrated_motion_seconds(10.0, 0.0)

    def test_default_program_is_self_contained_non_z_pen_contract(self):
        contours = [[(-25.0, 0.0), (25.0, 0.0)]]
        gcode = converter.contours_to_gcode(contours, converter.Settings())
        lines = gcode.splitlines()

        self.assertEqual(lines[:9], [
            "(Generated by svg_to_gcode.pyw)",
            "(theta ratio 12.03324 motor deg per bed deg, offset 0.000)",
            "(feed 700.0 mm/min, travel 3000.0 mm/min, tolerance 0.250 mm, pen 0.20 mm)",
            "G21",
            "G90",
            "G94",
            "G17",
            "G54",
            "G0 F3000",
        ])
        self.assertIn("M5", lines)
        self.assertIn("M3", lines)
        self.assertNotRegex(gcode, r"(?m)(?:^|\s)Z[-+0-9.]")
        self.assertTrue(any(line.startswith("G1 ") and " A" in line for line in lines))

    def test_default_program_avoids_the_uncommissioned_gp27_handshake(self):
        # `G65 P115` is a fatal guard: when GP27/PRB does not show a fresh
        # inactive-to-active edge, its bounded timeout raises error 39 and the
        # controller aborts the streaming program mid-print. F-05A (the on-bench
        # P115 validation) is still open, so the shipped default must emit the
        # fixed G4 dwells; the handshake stays an explicit opt-in.
        contours = [[(-25.0, 0.0), (25.0, 0.0)]]
        settings = converter.Settings()
        self.assertFalse(settings.toolhead_status_handshake)

        lines = converter.contours_to_gcode(contours, settings).splitlines()

        self.assertFalse(
            [line for line in lines if line.startswith("G65 P115")],
            "default program must not emit the uncommissioned P115 handshake",
        )
        self.assertIn("M5", lines)
        self.assertIn("M3", lines)
        self.assertTrue(any(line.startswith("G4 P") for line in lines))

    def test_commissioned_gp27_handshake_replaces_fixed_pen_dwells(self):
        contours = [[(-25.0, 0.0), (25.0, 0.0)]]
        gcode = converter.contours_to_gcode(
            contours,
            converter.Settings(toolhead_status_handshake=True),
        )
        lines = gcode.splitlines()

        # The opening M5 may already be clear. Every later transition must
        # prove a new GP27 low-to-high completion edge before motion continues.
        self.assertIn("M5", lines)
        self.assertIn("M3", lines)
        # One opening-clear Q0 and one end-of-print full-retract Q0.
        self.assertEqual(lines.count("G65 P115 Q0"), 2)
        self.assertEqual(sum(line.startswith("G65 P115 Q1") for line in lines), 2)
        self.assertIn("M65 P0", lines)
        self.assertIn("M64 P0", lines)
        self.assertNotIn("G4 P0.3", lines)
        self.assertNotIn("G4 P0.6", lines)

        first_m3 = lines.index("M3")
        # The first pen-down seeks the whole GP2 retract distance, so it carries
        # a bound wide enough for that measured ~7 s seek.
        self.assertEqual(lines[first_m3 + 1], "G65 P115 Q1 B12")
        self.assertTrue(lines[first_m3 + 2].startswith("G1 F"))
        self.assertIn("G65 P115 Q1", lines)

    def test_handshake_first_down_bound_tracks_the_configured_first_dwell(self):
        contours = [[(-25.0, 0.0), (25.0, 0.0)]]
        gcode = converter.contours_to_gcode(
            contours,
            converter.Settings(toolhead_status_handshake=True, pen_down_first_ms=5000.0),
        )
        lines = gcode.splitlines()

        first_m3 = lines.index("M3")
        self.assertEqual(lines[first_m3 + 1], "G65 P115 Q1 B7")

    def test_handshake_recover_emits_lift_and_continue_flag(self):
        contours = [[(-25.0, 0.0), (25.0, 0.0)]]
        gcode = converter.contours_to_gcode(
            contours,
            converter.Settings(
                toolhead_status_handshake=True,
                toolhead_handshake_recover=True,
            ),
        )
        lines = gcode.splitlines()
        handshake_lines = [line for line in lines if line.startswith("G65 P115")]

        # Opening clear, first down, and the M5 transition recover by lifting
        # the pen (W2) with the pen-up dwell as the fallback; the end-of-print
        # full retract stays warn-only (W1) with the fixed 3 s retract dwell.
        self.assertEqual(
            handshake_lines,
            [
                "G65 P115 Q0 A0.8 W2",
                "G65 P115 Q1 B12 A0.8 W2",
                "G65 P115 Q1 A0.8 W2",
                "G65 P115 Q0 A3 W1",
            ],
        )
        self.assertFalse(converter.Settings().toolhead_handshake_recover)

    def test_gp27_handshake_rejects_non_m3_m5_pen_contract(self):
        with self.assertRaisesRegex(ValueError, "M5 pen-up"):
            converter.validate_settings(
                converter.Settings(
                    toolhead_status_handshake=True,
                    pen_up_command="",
                )
            )
        with self.assertRaisesRegex(ValueError, "M3 pen-down"):
            converter.validate_settings(
                converter.Settings(
                    toolhead_status_handshake=True,
                    pen_down_command="G4 P0.2",
                )
            )
        with self.assertRaisesRegex(ValueError, "disable Use Z axis"):
            converter.validate_settings(
                converter.Settings(toolhead_status_handshake=True, include_z=True)
            )

    def test_svg_coordinates_are_centered_in_g54_before_emission_and_preview(self):
        contours = [[(100.0, 100.0), (150.0, 100.0), (100.0, 150.0)]]
        settings = self.settings()
        program_plan = converter.plan_program(contours, settings)
        gcode = converter.contours_to_gcode(contours, settings, program_plan)
        preview_moves = converter.build_preview_moves(contours, settings, program_plan=program_plan)

        self.assertEqual(program_plan["source_center"], (125.0, 125.0))
        self.assertEqual(program_plan["center"], (0.0, 0.0))
        self.assertIn("G0 X-25 Y-25 A0", gcode.splitlines())
        first_travel = next(move for move in preview_moves if move["type"] == "travel")
        self.assertEqual(first_travel["end"], (-25.0, -25.0))

    def test_program_ends_with_machine_home_park(self):
        settings = self.settings(park_x_machine=-10.0, park_y_machine=-436.0)
        gcode = converter.contours_to_gcode([[(0.0, 0.0), (20.0, 0.0)]], settings)
        lines = gcode.splitlines()

        self.assertEqual(lines[-1], "M2")
        self.assertEqual(lines[-2], "G53 G0 X-10 Y-436 (park home)")

    def test_machine_reach_radius_caps_the_drawable_area(self):
        settings = self.settings(
            bed_diameter_mm=457.2,
            bed_margin_mm=0.0,
            machine_reach_radius_mm=50.0,
        )
        gcode = converter.contours_to_gcode([[(0.0, 0.0), (200.0, 0.0)]], settings)
        xs = [
            float(m.group(1))
            for line in gcode.splitlines()
            if "G53" not in line
            for m in [re.search(r"X(-?[0-9.]+)", line)]
            if m
        ]
        self.assertLessEqual(max(abs(x) for x in xs), 50.0 + 1e-4)
        self.assertGreaterEqual(max(abs(x) for x in xs), 45.0)

    def test_m06_radius_sweep_is_centered_and_stays_within_one_bed_step(self):
        """The M-06 sweep is the diagnostic that used to ask for huge sweeps.

        It is centred and its radii are right, and - the point of this contract -
        no single commanded move rotates the bed further than
        ``MAX_BED_STEP_DEG``, because beyond that the gantry can trace the same
        bed-space line with the bed parked instead of swinging it.
        """
        sample = Path(__file__).resolve().parents[2] / "samples" / "svg" / "m06-radius-sweep.svg"
        settings = self.settings(
            compensate_pen_width=False,
            pen_up_command="",
            pen_down_command="",
            pen_up_ms=0.0,
            pen_down_ms=0.0,
            toolhead_status_handshake=False,
        )
        contours = converter.read_svg(sample, settings)
        program_plan = converter.plan_program(contours, settings)
        gcode = converter.contours_to_gcode(contours, settings, program_plan)

        self.assertEqual(program_plan["source_center"], (100.0, 100.0))
        self.assertEqual(program_plan["center"], (0.0, 0.0))
        radii = {
            round(math.hypot(x, y), 3)
            for contour in program_plan["contours"]
            for x, y in contour
        }
        self.assertTrue({20.0, 50.0, 80.0}.issubset(radii))

        deltas = []
        for contour in re.split(r"(?=\(contour )", gcode):
            a_values = [
                float(match.group(1))
                for line in contour.splitlines()
                if line.startswith("G1 ")
                for match in [re.search(r"\bA([-+0-9.]+)", line)]
                if match
            ]
            deltas.extend(b - a for a, b in zip(a_values, a_values[1:]))
        limit = kinematics.MAX_BED_STEP_DEG * settings.theta_drive_ratio
        self.assertTrue(deltas, "the sweep must still move the bed where it can")
        self.assertLessEqual(
            max(abs(delta) for delta in deltas),
            limit + 1e-6,
            "no single move may command more than one safe bed step",
        )

    def test_m06_xy_theta_lettering_parks_the_bed_at_the_singularity(self):
        """Centre-crossing strokes used to swing the bed ~80 degrees in one move.

        The lettering sample crosses the bed centre, so the axis-lock roots sit
        far apart. The planner must park the bed and let the gantry trace those
        strokes in X and Y, and every rotating move it does emit must stay inside
        one safe bed step.
        """
        sample = Path(__file__).resolve().parents[2] / "samples" / "svg" / "m06-xy-theta-lettering.svg"
        settings = self.settings(
            pen_up_command="",
            pen_down_command="",
            pen_up_ms=0.0,
            pen_down_ms=0.0,
            toolhead_status_handshake=False,
        )
        contours = converter.read_svg(sample, settings)
        gcode = converter.contours_to_gcode(contours, settings)

        self.assertIn("(hold)", gcode, "a centre-crossing stroke must not swing the bed")
        deltas = []
        for contour in re.split(r"(?=\(contour )", gcode):
            a_values = [
                float(match.group(1))
                for line in contour.splitlines()
                if line.startswith("G1 ") or line.startswith("G0 ")
                for match in [re.search(r"\bA([-+0-9.]+)", line)]
                if match
            ]
            deltas.extend(b - a for a, b in zip(a_values, a_values[1:]))
        limit = kinematics.MAX_BED_STEP_DEG * settings.theta_drive_ratio
        for delta in deltas:
            self.assertLessEqual(abs(delta), limit + 1e-6)

    def test_fill_centred_on_the_bed_centre_stays_inside_the_axis_limits(self):
        """The print that stalled: a gradient fill centred on the bed centre.

        Rows a couple of millimetres from the centre used to be commanded with
        bed sweeps of tens of degrees inside a single move - 1333 motor deg/s at
        the controller's configured A rapid - which wrapped those rows around
        the centre on paper instead of drawing them straight. Nothing in the
        emitted program may ask for more than one safe bed step, or for an A rate
        above the converter's assumed limit, and no pen-up move may carry a bed
        rotation as a bare `G0` rapid.
        """
        svg = (
            '<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120" '
            'viewBox="-60 -60 120 120">'
            '<circle cx="0" cy="0" r="30" fill="#111111"/></svg>'
        )
        folder = tempfile.mkdtemp(prefix="theta-centre-")
        sample = Path(folder) / "centre.svg"
        sample.write_text(svg, encoding="utf-8")

        settings = self.settings(
            hatch_spacing_mm=2.0,
            hatch_pattern="sine_gradient",
            gradient_wave_amplitude_pct=40.0,
            gradient_wave_density_pct=0.0,
            sine_rows_connected=False,
            fit_mode="manual",
            scale=1.0,
            pen_up_command="",
            pen_down_command="",
            pen_up_ms=0.0,
            pen_down_ms=0.0,
            toolhead_status_handshake=False,
        )
        contours = converter.read_svg(sample, settings)
        program_plan = converter.plan_program(contours, settings)
        gcode = converter.contours_to_gcode(contours, settings, program_plan)

        ratio = settings.theta_drive_ratio
        step_limit = kinematics.MAX_BED_STEP_DEG * ratio
        rate_limit = settings.theta_controller_limits.max_rate_deg_min / 60.0
        previous = None
        worst_step = 0.0
        worst_rate = 0.0
        rapids_with_rotation = 0
        for line in gcode.splitlines():
            match = re.match(
                r"G([01]) X(-?[\d.]+) Y(-?[\d.]+)(?: A(-?[\d.]+))?(?: F([\d.]+))?", line
            )
            if not match:
                continue
            kind, x, y, a, feed = match.groups()
            point = (float(x), float(y), float(a) if a is not None else None)
            if previous is not None and point[2] is not None and previous[2] is not None:
                delta = abs(point[2] - previous[2])
                if "(travel)" not in line:
                    worst_step = max(worst_step, delta)
                if delta > 1e-9:
                    if kind == "0":
                        rapids_with_rotation += 1
                    elif feed:
                        xy = math.hypot(point[0] - previous[0], point[1] - previous[1])
                        seconds = (math.hypot(xy, delta) / float(feed)) * 60.0
                        if seconds > 0.0:
                            worst_rate = max(worst_rate, delta / seconds)
            previous = (point[0], point[1], point[2])

        self.assertLessEqual(worst_step, step_limit + 1e-6)
        self.assertLessEqual(worst_rate, rate_limit * 1.01)
        self.assertEqual(rapids_with_rotation, 0, "a pen-up rotation must be fed, not a rapid")

    def test_the_bed_step_cap_is_hard_at_any_setting(self):
        """Lowering the cap must bound every drawing move, not just most of them.

        The parked bed can always trace an in-disc move, so there is no segment
        that needs a bigger sweep - the cap is a limit, not a preference the
        travel cost can overrule.
        """
        design = converter.random_pattern(
            seed=83382, intricacy=10, radius_mm=181.0, wedge_deg=15.0
        )
        for cap in (15.0, 10.0, 5.0):
            settings = converter.Settings(
                fit_mode="manual", scale=1.0, flip_y=False, theta_max_step_deg=cap
            )
            gcode = converter.contours_to_gcode(design, settings)
            ratio = settings.theta_drive_ratio
            previous = None
            worst = 0.0
            for line in gcode.splitlines():
                match = re.match(
                    r"G1 X(-?[\d.]+) Y(-?[\d.]+)(?: A(-?[\d.]+))?", line
                )
                if not match:
                    continue
                x, y, a = match.groups()
                point = (float(x), float(y), float(a) if a is not None else None)
                if (
                    previous is not None
                    and point[2] is not None
                    and previous[2] is not None
                    and "(travel)" not in line
                ):
                    worst = max(worst, abs(point[2] - previous[2]))
                previous = point
            self.assertLessEqual(
                worst,
                cap * ratio + 1e-6,
                "cap %g deg: no drawing move may exceed it" % cap,
            )

    def test_invalid_machine_motion_settings_are_rejected(self):
        for kwargs in (
            {"feed_rate": 0.0},
            {"travel_rate": -1.0},
            {"theta_drive_ratio": 0.0},
            {"theta_axis": "B"},
            {"bed_margin_mm": 230.0},
        ):
            with self.subTest(kwargs=kwargs):
                with self.assertRaises(ValueError):
                    converter.contours_to_gcode([[(0.0, 0.0), (10.0, 0.0)]], converter.Settings(**kwargs))

    def test_preview_only_theta_omission_mode_is_not_available(self):
        self.assertFalse(hasattr(converter.Settings(), "preview_xy_only"))
        self.assertNotIn(
            "preview_xy_only",
            " ".join(key for _group, key, _label, _default in converter.CHECKBOX_FIELDS),
        )

    def test_forward_and_reverse_a_moves_have_the_same_feed_plan(self):
        forward = self.plan_at_radius(100.0, motor_delta=100.0)
        reverse = self.plan_at_radius(100.0, motor_delta=-100.0)

        self.assertAlmostEqual(forward["feed_rate"], reverse["feed_rate"])
        self.assertAlmostEqual(forward["a_rate_deg_min"], reverse["a_rate_deg_min"])

    def test_a_rate_and_acceleration_limits_are_applied(self):
        rate_limited = self.plan_at_radius(
            50.0,
            theta_controller_limits=converter.ThetaControllerLimits(
                max_rate_deg_min=1000.0,
                max_acceleration_deg_s2=1_000_000_000.0,
            ),
        )
        accel_limited = self.plan_at_radius(
            100.0,
            motor_delta=1.0,
            theta_controller_limits=converter.ThetaControllerLimits(
                max_rate_deg_min=1_000_000.0,
                max_acceleration_deg_s2=4.0,
            ),
        )

        self.assertAlmostEqual(rate_limited["a_rate_deg_min"], 1000.0)
        self.assertIn("rate", rate_limited["limited_by"])
        self.assertAlmostEqual(accel_limited["a_rate_deg_min"], 120.0)
        self.assertIn("acceleration", accel_limited["limited_by"])

    def test_center_move_is_finite_and_has_zero_tangential_speed(self):
        plan = converter.plan_radius_aware_draw_feed(
            self.CENTER,
            self.CENTER,
            self.CENTER,
            0.0,
            10.0,
            self.settings(),
        )

        self.assertEqual(plan["radius_mm"], 0.0)
        self.assertEqual(plan["tangential_speed_mm_min"], 0.0)
        self.assertTrue(math.isfinite(plan["feed_rate"]))
        self.assertTrue(math.isfinite(plan["duration_ms"]))

    def test_no_a_move_retains_the_xy_feed_rate(self):
        plan = converter.plan_radius_aware_draw_feed(
            (0.0, 0.0),
            (100.0, 0.0),
            self.CENTER,
            100.0,
            0.0,
            self.settings(feed_rate=987.0),
        )

        self.assertEqual(plan["feed_rate"], 987.0)
        self.assertEqual(plan["duration_ms"], 100.0 / 987.0 * 60000.0)

    def test_preview_draw_blocks_match_generated_gcode(self):
        contours = [[(-50.0, -10.0), (0.0, 15.0), (50.0, 30.0)]]
        settings = self.settings(include_z=False)
        program_plan = converter.plan_program(contours, settings)
        gcode = converter.contours_to_gcode(contours, settings, program_plan)
        draw_moves = [
            move
            for move in converter.build_preview_moves(contours, settings, program_plan=program_plan)
            if move["type"] == "draw"
        ]

        self.assertTrue(draw_moves)
        self.assertTrue(any(" A" in move["gcode"] for move in draw_moves))
        for move in draw_moves:
            self.assertIn(move["gcode"], gcode)
            match = re.search(r"\bF([-+0-9.]+)", move["gcode"])
            self.assertIsNotNone(match)
            self.assertAlmostEqual(float(match.group(1)), move["feed_rate"], places=4)

    def test_shared_program_plan_does_not_replan_for_preview_and_gcode(self):
        contours = [[(-50.0, -10.0), (0.0, 15.0), (50.0, 30.0)]]
        settings = self.settings()
        original = gcode_module.plan_contour_thetas
        with patch.object(gcode_module, "plan_contour_thetas", wraps=original) as planner:
            program_plan = converter.plan_program(contours, settings)
            converter.build_preview_moves(contours, settings, program_plan=program_plan)
            converter.contours_to_gcode(contours, settings, program_plan)
        self.assertEqual(planner.call_count, len(program_plan["planned_jobs"]))

    def test_fixed_theta_output_is_unchanged_by_tangential_setting(self):
        contours = [[(-25.0, 0.0), (25.0, 0.0)]]
        baseline = self.settings(theta_mode="fixed", theta_tangential_speed_mm_min=1200.0)
        changed = self.settings(theta_mode="fixed", theta_tangential_speed_mm_min=300.0)

        self.assertEqual(
            converter.contours_to_gcode(contours, baseline),
            converter.contours_to_gcode(contours, changed),
        )


if __name__ == "__main__":
    unittest.main()
