import math
import re
import sys
import unittest
from pathlib import Path
from unittest.mock import patch


sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import converter_core as converter
import converter_core.gcode as gcode_module


class RadiusAwareThetaFeedTests(unittest.TestCase):
    CENTER = (0.0, 0.0)

    def settings(self, **kwargs):
        defaults = {
            "feed_rate": 1200.0,
            "theta_tangential_speed_mm_min": 1200.0,
            "theta_controller_limits": converter.ThetaControllerLimits(
                max_rate_deg_min=1_000_000.0,
                max_acceleration_deg_s2=1_000_000_000.0,
            ),
        }
        defaults.update(kwargs)
        return converter.Settings(**defaults)

    def plan_at_radius(self, radius, motor_delta=100.0, **kwargs):
        return converter.plan_radius_aware_draw_feed(
            (radius, 0.0),
            (radius, 0.0),
            self.CENTER,
            0.0,
            motor_delta,
            self.settings(**kwargs),
        )

    def test_required_a_rate_is_inverse_to_radius(self):
        inner = self.plan_at_radius(50.0)
        outer = self.plan_at_radius(100.0)

        self.assertAlmostEqual(inner["a_rate_deg_min"], outer["a_rate_deg_min"] * 2.0)
        self.assertAlmostEqual(inner["tangential_speed_mm_min"], 1200.0)
        self.assertAlmostEqual(outer["tangential_speed_mm_min"], 1200.0)

    def test_tangential_speed_setting_is_loaded_from_the_ui_value(self):
        settings = converter.settings_from_values(
            {"theta_tangential_speed_mm_min": "725.5"},
            {},
        )

        self.assertEqual(settings.theta_tangential_speed_mm_min, 725.5)

    def test_default_program_is_self_contained_non_z_pen_contract(self):
        contours = [[(-25.0, 0.0), (25.0, 0.0)]]
        gcode = converter.contours_to_gcode(contours, converter.Settings())
        lines = gcode.splitlines()

        self.assertEqual(lines[:7], [
            "(Generated by svg_to_gcode.pyw)",
            "G21",
            "G90",
            "G94",
            "G17",
            "G54",
            "G0 F3000",
        ])
        self.assertIn("M5", lines)
        self.assertIn("M3", lines)
        self.assertNotRegex(gcode, r"(?m)(?:^|\s)Z[-+0-9.]")
        self.assertTrue(any(line.startswith("G1 ") and " A" in line for line in lines))

    def test_svg_coordinates_are_centered_in_g54_before_emission_and_preview(self):
        contours = [[(100.0, 100.0), (150.0, 100.0), (100.0, 150.0)]]
        settings = self.settings()
        program_plan = converter.plan_program(contours, settings)
        gcode = converter.contours_to_gcode(contours, settings, program_plan)
        preview_moves = converter.build_preview_moves(contours, settings, program_plan=program_plan)

        self.assertEqual(program_plan["source_center"], (125.0, 125.0))
        self.assertEqual(program_plan["center"], (0.0, 0.0))
        self.assertIn("G0 X-25 Y-25 A0", gcode.splitlines())
        first_travel = next(move for move in preview_moves if move["type"] == "travel")
        self.assertEqual(first_travel["end"], (-25.0, -25.0))

    def test_ne_park_stays_inside_the_configured_drawable_bed(self):
        settings = self.settings(bed_diameter_mm=200.0, bed_margin_mm=10.0)
        gcode = converter.contours_to_gcode([[(0.0, 0.0), (20.0, 0.0)]], settings)
        park = next(line for line in gcode.splitlines() if "(park NE)" in line)
        match = re.search(r"X([-+0-9.]+) Y([-+0-9.]+)", park)

        self.assertIsNotNone(match)
        x, y = (float(match.group(1)), float(match.group(2)))
        self.assertLessEqual(math.hypot(x, y), 90.0 + 1e-4)

    def test_m06_radius_sweep_is_centered_and_rotates_in_both_directions(self):
        sample = Path(__file__).resolve().parents[2] / "samples" / "svg" / "m06-radius-sweep.svg"
        settings = self.settings(
            compensate_pen_width=False,
            pen_up_command="",
            pen_down_command="",
            pen_up_ms=0.0,
            pen_down_ms=0.0,
        )
        contours = converter.read_svg(sample, settings)
        program_plan = converter.plan_program(contours, settings)
        gcode = converter.contours_to_gcode(contours, settings, program_plan)

        self.assertEqual(program_plan["source_center"], (100.0, 100.0))
        self.assertEqual(program_plan["center"], (0.0, 0.0))
        radii = {
            round(math.hypot(x, y), 3)
            for contour in program_plan["contours"]
            for x, y in contour
        }
        self.assertTrue({20.0, 50.0, 80.0}.issubset(radii))

        directions = []
        for contour in re.split(r"(?=\(contour )", gcode):
            a_values = [
                float(match.group(1))
                for line in contour.splitlines()
                if line.startswith("G1 ")
                for match in [re.search(r"\bA([-+0-9.]+)", line)]
                if match
            ]
            directions.extend(b - a for a, b in zip(a_values, a_values[1:]))
        self.assertTrue(any(delta > 1e-6 for delta in directions))
        self.assertTrue(any(delta < -1e-6 for delta in directions))

    def test_invalid_machine_motion_settings_are_rejected(self):
        for kwargs in (
            {"feed_rate": 0.0},
            {"travel_rate": -1.0},
            {"theta_drive_ratio": 0.0},
            {"theta_axis": "B"},
            {"bed_margin_mm": 230.0},
        ):
            with self.subTest(kwargs=kwargs):
                with self.assertRaises(ValueError):
                    converter.contours_to_gcode([[(0.0, 0.0), (10.0, 0.0)]], converter.Settings(**kwargs))

    def test_preview_only_theta_omission_mode_is_not_available(self):
        self.assertFalse(hasattr(converter.Settings(), "preview_xy_only"))
        self.assertNotIn(
            "preview_xy_only",
            " ".join(key for _group, key, _label, _default in converter.CHECKBOX_FIELDS),
        )

    def test_forward_and_reverse_a_moves_have_the_same_feed_plan(self):
        forward = self.plan_at_radius(100.0, motor_delta=100.0)
        reverse = self.plan_at_radius(100.0, motor_delta=-100.0)

        self.assertAlmostEqual(forward["feed_rate"], reverse["feed_rate"])
        self.assertAlmostEqual(forward["a_rate_deg_min"], reverse["a_rate_deg_min"])

    def test_a_rate_and_acceleration_limits_are_applied(self):
        rate_limited = self.plan_at_radius(
            50.0,
            theta_controller_limits=converter.ThetaControllerLimits(
                max_rate_deg_min=1000.0,
                max_acceleration_deg_s2=1_000_000_000.0,
            ),
        )
        accel_limited = self.plan_at_radius(
            100.0,
            motor_delta=1.0,
            theta_controller_limits=converter.ThetaControllerLimits(
                max_rate_deg_min=1_000_000.0,
                max_acceleration_deg_s2=4.0,
            ),
        )

        self.assertAlmostEqual(rate_limited["a_rate_deg_min"], 1000.0)
        self.assertIn("rate", rate_limited["limited_by"])
        self.assertAlmostEqual(accel_limited["a_rate_deg_min"], 120.0)
        self.assertIn("acceleration", accel_limited["limited_by"])

    def test_center_move_is_finite_and_has_zero_tangential_speed(self):
        plan = converter.plan_radius_aware_draw_feed(
            self.CENTER,
            self.CENTER,
            self.CENTER,
            0.0,
            10.0,
            self.settings(),
        )

        self.assertEqual(plan["radius_mm"], 0.0)
        self.assertEqual(plan["tangential_speed_mm_min"], 0.0)
        self.assertTrue(math.isfinite(plan["feed_rate"]))
        self.assertTrue(math.isfinite(plan["duration_ms"]))

    def test_no_a_move_retains_the_xy_feed_rate(self):
        plan = converter.plan_radius_aware_draw_feed(
            (0.0, 0.0),
            (100.0, 0.0),
            self.CENTER,
            100.0,
            0.0,
            self.settings(feed_rate=987.0),
        )

        self.assertEqual(plan["feed_rate"], 987.0)
        self.assertEqual(plan["duration_ms"], 100.0 / 987.0 * 60000.0)

    def test_preview_draw_blocks_match_generated_gcode(self):
        contours = [[(-50.0, -10.0), (0.0, 15.0), (50.0, 30.0)]]
        settings = self.settings(include_z=False)
        program_plan = converter.plan_program(contours, settings)
        gcode = converter.contours_to_gcode(contours, settings, program_plan)
        draw_moves = [
            move
            for move in converter.build_preview_moves(contours, settings, program_plan=program_plan)
            if move["type"] == "draw"
        ]

        self.assertTrue(draw_moves)
        self.assertTrue(any(" A" in move["gcode"] for move in draw_moves))
        for move in draw_moves:
            self.assertIn(move["gcode"], gcode)
            match = re.search(r"\bF([-+0-9.]+)", move["gcode"])
            self.assertIsNotNone(match)
            self.assertAlmostEqual(float(match.group(1)), move["feed_rate"], places=4)

    def test_shared_program_plan_does_not_replan_for_preview_and_gcode(self):
        contours = [[(-50.0, -10.0), (0.0, 15.0), (50.0, 30.0)]]
        settings = self.settings()
        original = gcode_module.plan_contour_thetas
        with patch.object(gcode_module, "plan_contour_thetas", wraps=original) as planner:
            program_plan = converter.plan_program(contours, settings)
            converter.build_preview_moves(contours, settings, program_plan=program_plan)
            converter.contours_to_gcode(contours, settings, program_plan)
        self.assertEqual(planner.call_count, len(program_plan["planned_jobs"]))

    def test_fixed_theta_output_is_unchanged_by_tangential_setting(self):
        contours = [[(-25.0, 0.0), (25.0, 0.0)]]
        baseline = self.settings(theta_mode="fixed", theta_tangential_speed_mm_min=1200.0)
        changed = self.settings(theta_mode="fixed", theta_tangential_speed_mm_min=300.0)

        self.assertEqual(
            converter.contours_to_gcode(contours, baseline),
            converter.contours_to_gcode(contours, changed),
        )


if __name__ == "__main__":
    unittest.main()
